/** GENERATED by tools/extract_alpha_spots.py — fixed alpha/boss spots
 * per pal, positions normalized to the game map image (game-file
 * coordinate transforms via palcalc). off=true: outside the base map
 * image (e.g. The World Tree) — shown as a label, never a fake pin. */
export interface AlphaSpot {
  place: string;
  lv: number | null;
  x: number;
  y: number;
  off: boolean;
}

export const ALPHA_SPOTS: Record<string, AlphaSpot[]> = {
 "Aegidron": [
  {
   "place": "The World Tree",
   "lv": 79,
   "x": 0.5906,
   "y": 0.0872,
   "off": false
  }
 ],
 "Anubis": [
  {
   "place": "Palpagos Islands",
   "lv": 55,
   "x": 0.5664,
   "y": 0.3565,
   "off": false
  }
 ],
 "Arsox": [
  {
   "place": "Palpagos Islands",
   "lv": 15,
   "x": 0.572,
   "y": 0.4823,
   "off": false
  }
 ],
 "Astegon": [
  {
   "place": "Palpagos Islands",
   "lv": 55,
   "x": 0.3896,
   "y": 0.3615,
   "off": false
  }
 ],
 "Azurmane": [
  {
   "place": "Palpagos Islands",
   "lv": 66,
   "x": 0.2483,
   "y": 0.8552,
   "off": false
  }
 ],
 "Azurobe": [
  {
   "place": "Palpagos Islands",
   "lv": 40,
   "x": 0.553,
   "y": 0.411,
   "off": false
  }
 ],
 "Beakon": [
  {
   "place": "Palpagos Islands",
   "lv": 37,
   "x": 0.6394,
   "y": 0.3194,
   "off": false
  }
 ],
 "Blazamut": [
  {
   "place": "Palpagos Islands",
   "lv": 52,
   "x": 0.3743,
   "y": 0.4319,
   "off": false
  }
 ],
 "Blazehowl": [
  {
   "place": "Palpagos Islands",
   "lv": 30,
   "x": 0.5275,
   "y": 0.3682,
   "off": false
  }
 ],
 "Broncherry": [
  {
   "place": "Palpagos Islands",
   "lv": 23,
   "x": 0.5382,
   "y": 0.5387,
   "off": false
  }
 ],
 "Bushi": [
  {
   "place": "Palpagos Islands",
   "lv": 25,
   "x": 0.5443,
   "y": 0.4363,
   "off": false
  }
 ],
 "Caprity Noct": [
  {
   "place": "Palpagos Islands",
   "lv": 23,
   "x": 0.5621,
   "y": 0.5355,
   "off": false
  }
 ],
 "Celesdir": [
  {
   "place": "The World Tree",
   "lv": 79,
   "x": 0.5903,
   "y": 0.0802,
   "off": false
  },
  {
   "place": "Palpagos Islands",
   "lv": 65,
   "x": 0.3013,
   "y": 0.698,
   "off": false
  }
 ],
 "Celesdir Noct": [
  {
   "place": "The World Tree",
   "lv": 79,
   "x": 0.5903,
   "y": 0.0802,
   "off": false
  }
 ],
 "Chillet": [
  {
   "place": "Palpagos Islands",
   "lv": 11,
   "x": 0.6638,
   "y": 0.4592,
   "off": false
  }
 ],
 "Cryolinx Terra": [
  {
   "place": "Palpagos Islands",
   "lv": 62,
   "x": 0.1994,
   "y": 0.7392,
   "off": false
  }
 ],
 "Dazzi Noct": [
  {
   "place": "Palpagos Islands",
   "lv": 60,
   "x": 0.2263,
   "y": 0.5976,
   "off": false
  }
 ],
 "Dinossom Lux": [
  {
   "place": "Palpagos Islands",
   "lv": 47,
   "x": 0.7095,
   "y": 0.2732,
   "off": false
  }
 ],
 "Dualith": [
  {
   "place": "The World Tree",
   "lv": 55,
   "x": 0.6142,
   "y": 0.0808,
   "off": false
  }
 ],
 "Dualith Noct": [
  {
   "place": "Palpagos Islands",
   "lv": 70,
   "x": 0.0692,
   "y": 0.627,
   "off": false
  }
 ],
 "Dumud": [
  {
   "place": "Palpagos Islands",
   "lv": 14,
   "x": 0.5104,
   "y": 0.3254,
   "off": false
  }
 ],
 "Dynamoff": [
  {
   "place": "Palpagos Islands",
   "lv": 67,
   "x": 0.5105,
   "y": 0.8093,
   "off": false
  }
 ],
 "Eidrolon": [
  {
   "place": "Palpagos Islands",
   "lv": 69,
   "x": 0.4528,
   "y": 0.8086,
   "off": false
  }
 ],
 "Elizabee": [
  {
   "place": "Palpagos Islands",
   "lv": 39,
   "x": 0.6613,
   "y": 0.3533,
   "off": false
  }
 ],
 "Elphidran": [
  {
   "place": "Palpagos Islands",
   "lv": 30,
   "x": 0.623,
   "y": 0.4167,
   "off": false
  }
 ],
 "Eye of Cthulhu": [
  {
   "place": "Sealed Realm of Terraria, Eternal Summer Isle",
   "lv": 45,
   "x": 0.4744,
   "y": 0.5786,
   "off": false
  }
 ],
 "Faleris Aqua": [
  {
   "place": "Palpagos Islands",
   "lv": 66,
   "x": 0.1926,
   "y": 0.84,
   "off": false
  }
 ],
 "Fenglope": [
  {
   "place": "Palpagos Islands",
   "lv": 25,
   "x": 0.5268,
   "y": 0.4718,
   "off": false
  }
 ],
 "Fenglope Lux": [
  {
   "place": "Palpagos Islands",
   "lv": 60,
   "x": 0.3354,
   "y": 0.6898,
   "off": false
  }
 ],
 "Flaracle": [
  {
   "place": "Serving Seer Flaracle (Lv. 68) - Palpagos Islands",
   "lv": null,
   "x": 0.5309,
   "y": 0.8083,
   "off": false
  }
 ],
 "Foxcicle": [
  {
   "place": "Palpagos Islands",
   "lv": 15,
   "x": 0.6861,
   "y": 0.4319,
   "off": false
  }
 ],
 "Foxparks Cryst": [
  {
   "place": "Palpagos Islands",
   "lv": 15,
   "x": 0.4782,
   "y": 0.3441,
   "off": false
  }
 ],
 "Frostallion": [
  {
   "place": "Palpagos Islands",
   "lv": 60,
   "x": 0.4956,
   "y": 0.1654,
   "off": false
  }
 ],
 "Frostallion Noct": [
  {
   "place": "Palpagos Islands",
   "lv": 65,
   "x": 0.8288,
   "y": 0.1214,
   "off": false
  }
 ],
 "Gildane": [
  {
   "place": "Palpagos Islands",
   "lv": 63,
   "x": 0.3092,
   "y": 0.7741,
   "off": false
  }
 ],
 "Grintale": [
  {
   "place": "Palpagos Islands",
   "lv": 17,
   "x": 0.7224,
   "y": 0.4047,
   "off": false
  }
 ],
 "Grizzbolt": [
  {
   "place": "Palpagos Islands",
   "lv": 30,
   "x": 0.6267,
   "y": 0.5476,
   "off": false
  }
 ],
 "Gumoss": [
  {
   "place": "Palpagos Islands",
   "lv": 11,
   "x": 0.5729,
   "y": 0.5257,
   "off": false
  }
 ],
 "Jetragon": [
  {
   "place": "Palpagos Islands",
   "lv": 70,
   "x": 0.4325,
   "y": 0.7487,
   "off": false
  }
 ],
 "Jormuntide": [
  {
   "place": "Palpagos Islands",
   "lv": 55,
   "x": 0.7206,
   "y": 0.3536,
   "off": false
  }
 ],
 "Kingpaca": [
  {
   "place": "Palpagos Islands",
   "lv": 23,
   "x": 0.6249,
   "y": 0.4725,
   "off": false
  }
 ],
 "Kingpaca Cryst": [
  {
   "place": "Palpagos Islands",
   "lv": 46,
   "x": 0.4866,
   "y": 0.2139,
   "off": false
  }
 ],
 "Kitsun Noct": [
  {
   "place": "Palpagos Islands",
   "lv": 65,
   "x": 0.3389,
   "y": 0.7408,
   "off": false
  }
 ],
 "Knocklem": [
  {
   "place": "Palpagos Islands",
   "lv": 55,
   "x": 0.4227,
   "y": 0.4059,
   "off": false
  }
 ],
 "Loupmoon Cryst": [
  {
   "place": "Palpagos Islands",
   "lv": 66,
   "x": 0.2433,
   "y": 0.7747,
   "off": false
  }
 ],
 "Lunaris": [
  {
   "place": "Palpagos Islands",
   "lv": 35,
   "x": 0.6502,
   "y": 0.3426,
   "off": false
  }
 ],
 "Lyleen": [
  {
   "place": "59) - Palpagos Islands",
   "lv": null,
   "x": 0.4079,
   "y": 0.231,
   "off": false
  }
 ],
 "Lyleen Noct": [
  {
   "place": "59) - Palpagos Islands",
   "lv": null,
   "x": 0.4092,
   "y": 0.2304,
   "off": false
  }
 ],
 "Mammorest": [
  {
   "place": "Palpagos Islands",
   "lv": 38,
   "x": 0.6692,
   "y": 0.4782,
   "off": false
  }
 ],
 "Menasting": [
  {
   "place": "Palpagos Islands",
   "lv": 44,
   "x": 0.7208,
   "y": 0.1566,
   "off": false
  }
 ],
 "Menasting Terra": [
  {
   "place": "Piercing Spear Menasting Terra (Lv. 55) - Palpagos Islands",
   "lv": null,
   "x": 0.4238,
   "y": 0.2263,
   "off": false
  }
 ],
 "Moldron": [
  {
   "place": "Palpagos Islands",
   "lv": 70,
   "x": 0.2498,
   "y": 0.9544,
   "off": false
  }
 ],
 "Moldron Cryst": [
  {
   "place": "The World Tree",
   "lv": 78,
   "x": 0.5887,
   "y": 0.0682,
   "off": false
  }
 ],
 "Mossanda Lux": [
  {
   "place": "Palpagos Islands",
   "lv": 31,
   "x": 0.7517,
   "y": 0.3841,
   "off": false
  }
 ],
 "Mycora": [
  {
   "place": "The World Tree",
   "lv": 78,
   "x": 0.5982,
   "y": 0.0951,
   "off": false
  }
 ],
 "Necromus": [
  {
   "place": "Palpagos Islands",
   "lv": 60,
   "x": 0.7495,
   "y": 0.1116,
   "off": false
  }
 ],
 "Needoll": [
  {
   "place": "Palpagos Islands",
   "lv": 40,
   "x": 0.7468,
   "y": 0.552,
   "off": false
  }
 ],
 "Neptilius": [
  {
   "place": "Palpagos Islands",
   "lv": 60,
   "x": 0.6536,
   "y": 0.1204,
   "off": false
  }
 ],
 "Nitemary": [
  {
   "place": "Palpagos Islands",
   "lv": 60,
   "x": 0.3148,
   "y": 0.648,
   "off": false
  }
 ],
 "Nitewing": [
  {
   "place": "Palpagos Islands",
   "lv": 18,
   "x": 0.5212,
   "y": 0.3489,
   "off": false
  }
 ],
 "Nyafia": [
  {
   "place": "Palpagos Islands",
   "lv": 60,
   "x": 0.3158,
   "y": 0.6172,
   "off": false
  }
 ],
 "Omascul": [
  {
   "place": "Faced Apostle Omascul (Lv. 60) - Palpagos Islands",
   "lv": null,
   "x": 0.3833,
   "y": 0.6214,
   "off": false
  }
 ],
 "Ophydia": [
  {
   "place": "Palpagos Islands",
   "lv": 69,
   "x": 0.4207,
   "y": 0.795,
   "off": false
  }
 ],
 "Paladius": [
  {
   "place": "Palpagos Islands",
   "lv": 60,
   "x": 0.7495,
   "y": 0.1116,
   "off": false
  }
 ],
 "Penking": [
  {
   "place": "Palpagos Islands",
   "lv": 15,
   "x": 0.6453,
   "y": 0.4382,
   "off": false
  }
 ],
 "Pierdon": [
  {
   "place": "Palpagos Islands",
   "lv": 50,
   "x": 0.8701,
   "y": 0.1788,
   "off": false
  }
 ],
 "Prixter Lux": [
  {
   "place": "Palpagos Islands",
   "lv": 70,
   "x": 0.1904,
   "y": 0.5206,
   "off": false
  }
 ],
 "Prunelia": [
  {
   "place": "Palpagos Islands",
   "lv": 63,
   "x": 0.1772,
   "y": 0.6334,
   "off": false
  }
 ],
 "Renjishi": [
  {
   "place": "The World Tree",
   "lv": 78,
   "x": 0.6272,
   "y": 0.0612,
   "off": false
  }
 ],
 "Reptyro": [
  {
   "place": "Devouring Juggernaut Reptyro (Lv. 50) - Palpagos Islands",
   "lv": null,
   "x": 0.4344,
   "y": 0.4639,
   "off": false
  }
 ],
 "Sibelyx": [
  {
   "place": "Palpagos Islands",
   "lv": 40,
   "x": 0.6894,
   "y": 0.3048,
   "off": false
  }
 ],
 "Silvegis": [
  {
   "place": "Palpagos Islands",
   "lv": 62,
   "x": 0.295,
   "y": 0.6508,
   "off": false
  }
 ],
 "Slowatt": [
  {
   "place": "Back Slowatt (Lv. 66) - Palpagos Islands",
   "lv": null,
   "x": 0.4918,
   "y": 0.7567,
   "off": false
  }
 ],
 "Smokie": [
  {
   "place": "Black Little Hero Smokie (Lv. 60) - Palpagos Islands",
   "lv": null,
   "x": 0.3286,
   "y": 0.7915,
   "off": false
  }
 ],
 "Snock": [
  {
   "place": "Palpagos Islands",
   "lv": 65,
   "x": 0.4911,
   "y": 0.7747,
   "off": false
  }
 ],
 "Splatterina": [
  {
   "place": "Palpagos Islands",
   "lv": 65,
   "x": 0.2649,
   "y": 0.7877,
   "off": false
  }
 ],
 "Starryon": [
  {
   "place": "Palpagos Islands",
   "lv": 63,
   "x": 0.3242,
   "y": 0.7364,
   "off": false
  }
 ],
 "Suzaku": [
  {
   "place": "Palpagos Islands",
   "lv": 45,
   "x": 0.7131,
   "y": 0.1737,
   "off": false
  }
 ],
 "Sweepa": [
  {
   "place": "Palpagos Islands",
   "lv": 11,
   "x": 0.5366,
   "y": 0.5146,
   "off": false
  }
 ],
 "Tarantriss": [
  {
   "place": "Palpagos Islands",
   "lv": 35,
   "x": 0.4998,
   "y": 0.4065,
   "off": false
  }
 ],
 "Tetroise": [
  {
   "place": "Palpagos Islands",
   "lv": 55,
   "x": 0.7478,
   "y": 0.2063,
   "off": false
  }
 ],
 "Tetroise Primo": [
  {
   "place": "Palpagos Islands",
   "lv": 60,
   "x": 0.264,
   "y": 0.7449,
   "off": false
  }
 ],
 "Univolt": [
  {
   "place": "Palpagos Islands",
   "lv": 31,
   "x": 0.5717,
   "y": 0.4988,
   "off": false
  }
 ],
 "Vaelet": [
  {
   "place": "Palpagos Islands",
   "lv": 27,
   "x": 0.603,
   "y": 0.4107,
   "off": false
  }
 ],
 "Verdash": [
  {
   "place": "Palpagos Islands",
   "lv": 35,
   "x": 0.6999,
   "y": 0.3235,
   "off": false
  }
 ],
 "Warsect Terra": [
  {
   "place": "Armored Warrior Warsect Terra (Lv. 64) - Palpagos Islands",
   "lv": null,
   "x": 0.2841,
   "y": 0.7183,
   "off": false
  }
 ],
 "Whalaska": [
  {
   "place": "Palpagos Islands",
   "lv": 55,
   "x": 0.5524,
   "y": 0.0599,
   "off": false
  }
 ],
 "Whalaska Ignis": [
  {
   "place": "The World Tree",
   "lv": 74,
   "x": 0.625,
   "y": 0.0786,
   "off": false
  }
 ],
 "Wistella": [
  {
   "place": "Palpagos Islands",
   "lv": 66,
   "x": 0.5347,
   "y": 0.7751,
   "off": false
  }
 ],
 "Wixen": [
  {
   "place": "Licked Furball Wixen (Lv. 28) - Palpagos Islands",
   "lv": null,
   "x": 0.6603,
   "y": 0.3974,
   "off": false
  }
 ],
 "Wumpo Botan": [
  {
   "place": "Palpagos Islands",
   "lv": 38,
   "x": 0.7521,
   "y": 0.3429,
   "off": false
  }
 ]
};
