/** GENERATED by tools/extract_gender_ratio.py — DO NOT EDIT.
 * Per-species male probability, datamined (palcalc v27
 * BreedingGenderProbability — the game's own gender table). Only the
 * skewed species are listed; everything else is 50/50. */

/** male probability for species NOT at 50/50 */
export const MALE_PROB_SKEWED: Record<string, number> = {
  "Amione": 0.4,
  "Bakemi": 0.4,
  "Bastigor": 0.6,
  "Beegarde": 0.1,
  "Bellanoir": 0.1,
  "Bellanoir Libero": 0.1,
  "Carnibora": 0.4,
  "Dandilord": 0.6,
  "Dazzi": 0.2,
  "Dazzi Noct": 0.2,
  "Elgrove": 0.6,
  "Elgrove Cryst": 0.6,
  "Elizabee": 0.1,
  "Kingpaca": 0.9,
  "Kingpaca Cryst": 0.9,
  "Knocklem": 0.7,
  "Knocklem Ignis": 0.7,
  "Lapure": 0.4,
  "Leafan": 0.4,
  "Lovander": 0.3,
  "Lullu": 0.3,
  "Lyleen": 0.3,
  "Lyleen Noct": 0.3,
  "Majex": 0.4,
  "Mimog": 0.8,
  "Mozzarina": 0.2,
  "Mycora": 0.3,
  "Nitemary": 0.4,
  "Nitemary Botan": 0.4,
  "Nyafia": 0.4,
  "Prunelia": 0.4,
  "Renjishi": 0.6,
  "Roujay": 0.6,
  "Sekhmet": 0.3,
  "Selyne": 0.2,
  "Shroomer": 0.55,
  "Solenne": 0.3,
  "Souffline": 0.4,
  "Splatterina": 0.38,
  "Venusa": 0.4,
  "Warsect": 0.85,
  "Warsect Terra": 0.85,
  "Whalaska": 0.58,
  "Whalaska Ignis": 0.42,
};

/** male probability for any species (default 0.5) */
export const maleProb = (name: string): number =>
  MALE_PROB_SKEWED[name] ?? 0.5;
