/** GENERATED by tools/fetch_map_icons.py — DO NOT EDIT.
 * The game's own map symbols; the web app serves them from /mapicons/. */
export const MAP_ICON_LAYERS = new Set(['alpha_pals', 'bounty_targets', 'chest', 'coal', 'crude_oil', 'dungeon', 'egg', 'fast_travel', 'merchant', 'mushrooms', 'note', 'npc', 'ore', 'pal_effigy', 'pal_merchant', 'paldium', 'pure_quartz', 'red_berries', 'sealed_realm', 'skill_fruit', 'soralite', 'sulfur', 'syndicate_tower']);
