/** GENERATED by tools/extract_utility_roles.py — DO NOT EDIT.
 * Utility squads mined from the game's own partner-skill text and
 * mount field (pals_1_0.json). Every effect string is the game's,
 * verbatim — no community sourcing involved. */
export interface UtilityPal { name: string; effect: string }

export const UTILITY_ROLES: Record<string, { label: string; pals: UtilityPal[] }> = {
  capture: {
    label: "Catching helpers",
    pals: [
      { name: "Gloopie", effect: "While in party, the capture gauge decreases 12~35% more slowly while the bars are not overlapping during the fishing minigame. (Does not stack)" },
      { name: "Wispaw", effect: "While in party, increases the capture rate when awarded a back bonus. (Does not stack)" },
      { name: "Muffly", effect: "While in party, increases the capture rate of Pals afflicted with Freeze. (Does not stack)" },
      { name: "Whalaska", effect: "Can be ridden. While in party, fishing minigames start with the capture gauge increased by 5~14%. Additionally, while the bars overlap, capture progress increases by 5~14%. (Does not stack)" },
      { name: "Whalaska Ignis", effect: "Can be ridden. While in party, fishing minigame begins with the capture gauge 7~17% higher than usual, and capture progress increases by 7~17% while the bars overlap. (Does not stack)" },
      { name: "Souffline", effect: "While in party, increases the capture rate of Pals afflicted with Ivy-Covered. (Does not stack)" },
    ],
  },
  efficiency: {
    label: "Work efficiency boosters",
    pals: [
      { name: "Gumoss", effect: "While in party, improves logging efficiency by 30~50% and reduces weight of all types of wood by 40~60%. (Does not stack)" },
      { name: "Rushoar", effect: "Can be ridden. While mounted, increases efficiency of destroying Stone by 500~2000%." },
      { name: "Fuddler", effect: "While in party, improves player mining efficiency by 30~60% and reduces Stone weight by 80~100%. (Does not stack)" },
      { name: "Eikthyrdeer", effect: "Can be ridden. Can perform a double jump while mounted and increases lumbering efficiency by 220~500%." },
      { name: "Ribbuny Botan", effect: "While in party, improves player's and Pals' Grass damage to enemy weak points by 25~40%. (Does not stack) Increases efficiency by 200~400% when working at a Weapon Workbench, Weapon Assembly Line, or other related facilities." },
      { name: "Mammorest", effect: "Can be ridden. While mounted, increases logging efficiency by 220~500% and mining efficiency by 500~2000%." },
      { name: "Mammorest Cryst", effect: "Can be ridden. While mounted, increases logging efficiency by 220~500% and mining efficiency by 500~2000%." },
      { name: "Digtoise", effect: "When activated, enters the Shell Spin state. Follows the player while spinning, increasing ore mining efficiency by 800~2000%." },
      { name: "Sekhmet", effect: "While at base, boosts Anubis's work speed by 20~40%. Increases efficiency by 30~60% if Sekhmet is also working at a Workbench, Workshop, or other related facilities. (Does not stack)" },
    ],
  },
  weight: {
    label: "Weight & carrying helpers",
    pals: [
      { name: "Cattiva", effect: "While in party, Cattiva helps carry supplies, increasing the player's max carrying capacity by 100~200. (Does not stack)" },
      { name: "Turtacle", effect: "While in party, reduces Ore weight by 80~100%. (Does not stack)" },
      { name: "Turtacle Terra", effect: "While in party, reduces weight of Sulfur and Coal by 80~100%. Also improves player's and Pals' Ground damage to enemy weak points by 80~100%. (Does not stack)" },
      { name: "Lunaris", effect: "While in party, spheres home in on Pals, and carrying capacity increases by 300~600. (Does not stack)" },
      { name: "Munchill", effect: "While in party, reduces the weight of ingredient and food by 30~60%. When paired with another Ice Pal, their Rot Speed also reduces by -80~-30%. (Does not stack)" },
      { name: "Finsider Ignis", effect: "While in party, Finsider Ignis helps carry supplies, reducing the weight of weapons in your inventory by 60~100%. Also improves player's and Pals' Fire damage to enemy weak points by 25~40%. (Does not" },
      { name: "Reptyro", effect: "Can be ridden. While in party, reduces weight of all types of ore by 30~60%. (Does not stack)" },
      { name: "Reptyro Cryst", effect: "Can be ridden. While in party, reduces weight of all types of ore by 35~65%. (Does not stack)" },
    ],
  },
  drops: {
    label: "Better drops & yields",
    pals: [
      { name: "Lamball", effect: "When activated, equips to the player and becomes a shield. Sometimes drops Wool when assigned to Ranch." },
      { name: "Cremis", effect: "While in party, increases Attack of Neutral Pals by 15~30%. (Does not stack) Sometimes drops Wool when assigned to Ranch." },
      { name: "Depresso", effect: "When activated, Depresso chugs an entire energy drink, increasing its Movement Speed and Work Speed by 100~900%. Sometimes drops Venom Gland when assigned to Ranch." },
      { name: "Penking", effect: "While in party, Fire Pals drop 40~80% more items when defeated. (Does not stack)" },
      { name: "Melpaca", effect: "Can be ridden. While in party, increases Kingpaca's Defense and Movement Speed. Sometimes drops Wool when assigned to Ranch." },
      { name: "Flambelle", effect: "While in party, recovers Health of the player and Party Pals by 0.1~0.5% per second outside of combat. (Does not stack) Sometimes drops Flame Organ when assigned to Ranch." },
      { name: "Rooby", effect: "While in party, increases Defense of Fire Pals by 15~30%. (Does not stack) Sometimes drops Flame Organ when assigned to Ranch." },
      { name: "Mau Cryst", effect: "Sometimes drops Iceorgan when assigned to Ranch." },
      { name: "Caprity", effect: "Sometimes drops Red Berries from its back when assigned to Ranch. While in party, restores 100~200 Pal\u2019s Hunger to the Pal with the lowest Hunger every 5 minutes. (Does not stack)" },
      { name: "Caprity Noct", effect: "Sometimes drops Venom Gland from its back when assigned to Ranch. While in party, restores 100~200 Pal\u2019s Hunger to the Pal with the lowest Hunger every 5 minutes. (Does not stack)" },
      { name: "Woolipop", effect: "Sometimes drops Cotton Candy when assigned to Ranch. While at a base, reduces Hunger depletion rate of Base Pals by -20~-10%. (Does not stack)" },
      { name: "Woolipop Terra", effect: "Sometimes drops Caramel Cotton Candy when assigned to Ranch. While at a base, reduces Hunger depletion rate of Base Pals by -25~-15%. (Does not stack)" },
      { name: "Mozzarina", effect: "Sometimes drops Milk when assigned to Ranch." },
      { name: "Sparkit", effect: "While in party, increases Attack of Electric Pals by 15~30%. (Does not stack) Sometimes drops Electric Organ when assigned to Ranch." },
      { name: "Kelpsea", effect: "While in party, increases Attack of Water Pals by 15~30%. (Does not stack) Sometimes drops Aquatic Pal Fluids when assigned to Ranch." },
      { name: "Kelpsea Ignis", effect: "While in party, increases Attack of Fire Pals by 15~30%. (Does not stack) Sometimes drops Flame Organ when assigned to Ranch." },
      { name: "Elphidran", effect: "Can be ridden as a flying mount. While flying, Movement Speed is increased. While in party, Dark Pals drop 40~80% more items when defeated. (Does not stack)" },
      { name: "Vaelet", effect: "While in party, Ground Pals drop 40~80% more items when defeated. (Does not stack) Sometimes drops various seeds when assigned to Ranch." },
      { name: "Beegarde", effect: "While in party, increases Elizabee's Attack. Sometimes drops Honey when assigned to Ranch." },
      { name: "Surfent", effect: "Can be ridden to travel on water. Sometimes drops Leather when assigned to Ranch." },
      { name: "Katress", effect: "While in party, Neutral Pals drop 40~80% more items when defeated. Also has a 10~50% chance to prevent Pal Sphere consumption when thrown. (Does not stack)" },
      { name: "Fenglope Lux", effect: "Can be ridden. Can double jump while mounted. While in party, Water Pals drop 40~80% more items when defeated. (Does not stack)" },
      { name: "Foxcicle", effect: "While in party, increases Attack of Ice Pals by 15~30%. (Does not stack) Sometimes drops Ice Organ when assigned to Ranch." },
      { name: "Menasting", effect: "While in party, player's Defense increases by 5~10%, and Electric Pals drop 40~80% more items when defeated. (Does not stack)" },
      { name: "Menasting Terra", effect: "While in party, player's Defense increases by 5~10%, and Electric Pals drop 40~80% more items when defeated. (Does not stack)" },
      { name: "Dumud", effect: "While in party, increases Attack of Ground Pals by 15~30%. (Does not stack) Sometimes drops High Quality Pal Oil when assigned to Ranch." },
      { name: "Dumud Gild", effect: "While in party, increases amount of Gold Coin dropped by enemies by +100~200%. Sometimes drops High Quality Pal Oil when assigned to Ranch, with a small chance to drop Gold Coin. (Does not stack)" },
      { name: "Blazehowl", effect: "Can be ridden. While in party, Grass Pals drop 40~80% more items when defeated. (Does not stack)" },
      { name: "Blazehowl Noct", effect: "Can be ridden. While in party, Neutral Pals drop 40~80% more items when defeated. (Does not stack)" },
      { name: "Shroomer", effect: "Can be ridden. Sometimes drops Mushroom or Cavern Mushroom when assigned to Ranch." },
      { name: "Cryolinx", effect: "While in party, Dragon Pals drop 40~80% more items when defeated. (Does not stack)" },
      { name: "Nitemary", effect: "While fighting together, Pals drop +100~200% more Pal Souls when defeated. (Does not stack)" },
      { name: "Faleris", effect: "Can be ridden as a flying mount. While in party, Ice Pals drop 40~80% more items when defeated. (Does not stack)" },
      { name: "Faleris Aqua", effect: "Can be ridden as a flying mount. While in party, Fire Pals drop 40~80% more items when defeated. (Does not stack)" },
      { name: "Enchanted Sword", effect: "While in party, Dark Pals drop 40~80% more items when defeated. (Does not stack)" },
    ],
  },
  glider: {
    label: "Glider pals",
    pals: [
      { name: "Celaray", effect: "While in party, modifies the performance of the equipped glider. Prevents fall damage and extends the duration of high-speed gliding." },
      { name: "Celaray Lux", effect: "While in party, modifies the performance of the equipped glider. Prevents fall damage and extends the duration of high-speed gliding." },
      { name: "Killamari", effect: "While in party, modifies the performance of the equipped glider. Enables gentle floating while gliding for an extended time." },
      { name: "Killamari Primo", effect: "While in party, modifies the performance of the equipped glider. Enables gentle floating while gliding for an extended time." },
      { name: "Galeclaw", effect: "While in party, modifies the performance of the equipped glider. Enables high-speed gliding and allows shooting with the right hand." },
    ],
  },
};

/** the dump's own mount typing — order is Paldex order; speed claims need a labelled community source */
export const MOUNTS: Record<'flying' | 'ground' | 'swim', string[]> = {
  flying: ["Nitewing", "Elphidran", "Elphidran Aqua", "Vanwyrm", "Vanwyrm Cryst", "Helzephyr", "Helzephyr Lux", "Beakon", "Beakon Cryst", "Ragnahawk", "Suzaku", "Suzaku Aqua", "Quivern", "Quivern Botan", "Astegon", "Eidrolon", "Eidrolon Ignis", "Dynamoff", "Roujay", "Faleris", "Faleris Aqua", "Shadowbeak", "Selyne", "Shaolong", "Xenolord", "Frostallion", "Frostallion Noct", "Jetragon", "Panthalus"],
  ground: ["Melpaca", "Kingpaca", "Kingpaca Cryst", "Rushoar", "Eikthyrdeer", "Eikthyrdeer Terra", "Direhowl", "Sweepa", "Univolt", "Univolt Cryst", "Arsox", "Grintale", "Tarantriss", "Polapup", "Polapup Terra", "Surfent Terra", "Fenglope", "Fenglope Lux", "Dinossom", "Dinossom Lux", "Mammorest", "Mammorest Cryst", "Pyrin", "Pyrin Noct", "Relaxaurus", "Relaxaurus Lux", "Rayhound", "Rayhound Cryst", "Reindrix", "Mossanda", "Mossanda Lux", "Chillet", "Chillet Ignis", "Moldron", "Moldron Cryst", "Palumba", "Broncherry", "Broncherry Aqua", "Braloha", "Kitsun", "Kitsun Noct", "Blazehowl", "Blazehowl Noct", "Maraith", "Shroomer", "Shroomer Noct", "Jormuntide Ignis", "Dazemu", "Yakumo", "Reptyro", "Reptyro Cryst", "Starryon", "Starryon Primo", "Wumpo", "Wumpo Botan", "Blazamut", "Blazamut Ryu", "Dualith", "Dualith Noct", "Tetroise", "Tetroise Primo", "Xenogard", "Whalaska", "Whalaska Ignis", "Gildane", "Bulldosu", "Celesdir", "Celesdir Noct", "Silvegis", "Azurmane", "Ophydia", "Aegidron", "Grizzbolt", "Bastigor", "Hartalis", "Paladius", "Necromus", "Blue Slime", "Green Slime", "Illuminant Slime", "Purple Slime", "Rainbow Slime", "Red Slime"],
  swim: ["Azurobe", "Azurobe Cryst", "Surfent", "Ghangler", "Ghangler Ignis", "Jormuntide", "Solmora", "Solmora Lux", "Neptilius"],
};
