#!/usr/bin/env python3
"""Generate mobile/src/data/alphaSpots.g.ts — fixed alpha/boss locations per
pal as normalized positions on the game map image.

Sources:
- kb data/pal_locations.json: alpha location strings with in-game map coords,
  e.g. "Guardian ... (Lv. 79) - The World Tree (-59,756)".
- palcalc GameConstants: WorldToMapMatrix (world -> in-game map coords) and
  WorldToImageMatrix (world -> normalized map-image coords), both read from
  the game files. Image position = B @ inv(A) @ map_coord.

Run: python tools/extract_alpha_spots.py /path/to/kb-clone
"""
import json
import re
import struct
import sys
from pathlib import Path

KB = Path(sys.argv[1] if len(sys.argv) > 1 else ".")
OUT = Path(__file__).resolve().parent.parent / "mobile" / "src" / "data" / "alphaSpots.g.ts"

# palcalc GameConstants (game-file values)
A = [
    [-4.830223727277094e-07, 0.0021796738568829717, -344.193826581459],
    [0.0021779338609583232, 1.3843765562632747e-06, 269.9073674619908],
    [0.0, 0.0, 1.0],
]
B = [
    [5.853358785966763e-10, 6.942623697264833e-07, 0.49957354110764096],
    [-6.900889463287533e-07, -3.9501572187562305e-10, 0.24117673696704256],
    [0.0, 0.0, 1.0],
]


def mat_inv3(m):
    a, b, c = m[0]
    d, e, f = m[1]
    g, h, i = m[2]
    det = a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)
    inv = [
        [(e * i - f * h) / det, (c * h - b * i) / det, (b * f - c * e) / det],
        [(f * g - d * i) / det, (a * i - c * g) / det, (c * d - a * f) / det],
        [(d * h - e * g) / det, (b * g - a * h) / det, (a * e - b * d) / det],
    ]
    return inv


def mat_mul3(m, n):
    return [
        [sum(m[r][k] * n[k][c] for k in range(3)) for c in range(3)]
        for r in range(3)
    ]


C = mat_mul3(B, mat_inv3(A))  # map coords -> normalized image coords


def map_to_image(x, y):
    ix = C[0][0] * x + C[0][1] * y + C[0][2]
    iy = C[1][0] * x + C[1][1] * y + C[1][2]
    return ix, iy


SPOT = re.compile(r"^(.*?)\s*(?:\(Lv\.\s*(\d+)\))?\s*-\s*(.+?)\s*\((-?\d+)\s*,\s*(-?\d+)\)\s*$")


def main() -> None:
    locs = json.loads((KB / "data/pal_locations.json").read_text(encoding="utf-8"))["pals"]
    out = {}
    off_map = 0
    for name, p in locs.items():
        spots = []
        for raw in p.get("alpha_locations") or []:
            m = SPOT.match(raw)
            if not m:
                continue
            title, lv, place, x, y = m.groups()
            ix, iy = map_to_image(float(x), float(y))
            on_map = -0.02 <= ix <= 1.02 and -0.02 <= iy <= 1.02
            if not on_map:
                off_map += 1
            spots.append({
                "place": place.strip(),
                "lv": int(lv) if lv else None,
                "x": round(min(max(ix, 0.0), 1.0), 4),
                "y": round(min(max(iy, 0.0), 1.0), 4),
                "off": not on_map,
            })
        if spots:
            out[name] = spots

    lines = [
        "/** GENERATED by tools/extract_alpha_spots.py — fixed alpha/boss spots",
        " * per pal, positions normalized to the game map image (game-file",
        " * coordinate transforms via palcalc). off=true: outside the base map",
        " * image (e.g. The World Tree) — shown as a label, never a fake pin. */",
        "export interface AlphaSpot {",
        "  place: string;",
        "  lv: number | null;",
        "  x: number;",
        "  y: number;",
        "  off: boolean;",
        "}",
        "",
        f"export const ALPHA_SPOTS: Record<string, AlphaSpot[]> = {json.dumps(out, indent=1)};",
    ]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(out)} pals, off-map spots: {off_map})")

    # sanity: a couple of known-on-map bosses
    for probe in ["Chillet", "Penking", "Anubis"]:
        if probe in out:
            print(" ", probe, out[probe][0])


if __name__ == "__main__":
    main()
