#!/usr/bin/env python3
"""Extract per-pal facts from palcalc's db.json that our kb extraction lacks.

palcalc (github.com/tylercamp/palcalc) mirrors DT_PalMonsterParameter, so it
carries two things the kb dump buckets away or drops entirely:

  * ``Rarity``      — the game's own integer (1..10, 20 for the legendaries).
                      kb only exposes the four bucket words, so "how rare is
                      this really" is unanswerable from kb alone.
  * ``MinWildLevel`` — the FLOOR of the wild level range. kb gives only the
                      ceiling, which is why the app could say "wild up to
                      Lv 13" but never "from Lv 6".

Cross-validated on 2026-08-15: palcalc's MaxWildLevel agrees with our kb
``max_wild_level`` on all 285 pals that carry one — zero mismatches — so the
two dumps are the same game version and the floor can be trusted alongside it.

    python3 tools/extract_palcalc_facts.py [/path/to/palcalc/PalCalc.Model]

With no argument it fetches db.json from the pinned upstream URL.
Writes mobile/src/data/palcalcFacts.g.ts and app/src/data/palcalcFacts.g.ts.
"""
import json
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB_URL = "https://raw.githubusercontent.com/tylercamp/palcalc/main/PalCalc.Model/db.json"
OUT = [
    ROOT / "mobile" / "src" / "data" / "palcalcFacts.g.ts",
    ROOT / "app" / "src" / "data" / "palcalcFacts.g.ts",
]

HEADER = """/** GENERATED by tools/extract_palcalc_facts.py — DO NOT EDIT.
 * Per-pal facts straight from the game table via palcalc {version}
 * (github.com/tylercamp/palcalc, DT_PalMonsterParameter mirror).
 *
 *   rarity  — the game's own integer. 1..10, and 20 for the legendaries.
 *             kb's four bucket words map to it exactly:
 *             Common 1-4 · Rare 5-7 · Epic 8-10 · Legendary 20.
 *             (One disagreement, recorded not hidden: Gumoss is Common in kb
 *             and 10 in the game table.)
 *   minWild / maxWild — the wild level range. null = never spawns wild
 *             (raid/tower/boss-only pals).
 *   passives — GUARANTEED passive skills this species is always born with
 *             (English names, from GuaranteedPassivesInternalIds). Omitted
 *             when empty.
 *
 * Cross-validated {date}: maxWild agrees with the kb extraction on all
 * 285 pals that carry one, zero mismatches.
 */
export interface PalcalcFacts {{
  rarity: number;
  minWild: number | null;
  maxWild: number | null;
  passives?: string[];
}}

export const PALCALC_FACTS: Record<string, PalcalcFacts> = {{
"""


def load_db(argv: list[str]) -> dict:
    if len(argv) > 1:
        p = Path(argv[1])
        if p.is_dir():
            p = p / "db.json"
        return json.loads(p.read_text(encoding="utf-8"))
    print(f"fetching {DB_URL}")
    with urllib.request.urlopen(DB_URL) as r:  # noqa: S310 - pinned upstream
        return json.loads(r.read().decode("utf-8"))


def main() -> int:
    db = load_db(sys.argv)
    version = db.get("Version", "unknown")
    ours = json.loads((ROOT / "data" / "pals_1_0.json").read_text(encoding="utf-8"))["pals"]

    passive_names = {
        s["InternalName"]: (s.get("LocalizedNames") or {}).get("en") or s["Name"]
        for s in db.get("PassiveSkills", [])
    }
    facts: dict[str, dict] = {}
    for p in db["Pals"]:
        name = p["LocalizedNames"]["en"]
        guaranteed = [
            passive_names.get(i, i)
            for i in (p.get("GuaranteedPassivesInternalIds") or [])
        ]
        facts[name] = {
            "rarity": p["Rarity"],
            "minWild": p.get("MinWildLevel"),
            "maxWild": p.get("MaxWildLevel"),
            "passives": guaranteed,
        }

    # --- guard rails: never ship a silently-drifted dump -------------------
    missing = sorted(n for n in ours if n not in facts)
    extra = sorted(n for n in facts if n not in ours)
    clashes = [
        (n, ours[n]["max_wild_level"], facts[n]["maxWild"])
        for n in ours
        if n in facts
        and ours[n].get("max_wild_level") is not None
        and facts[n]["maxWild"] != ours[n]["max_wild_level"]
    ]
    print(f"palcalc {version}: {len(facts)} pals; ours {len(ours)}")
    print(f"  in ours but not palcalc: {missing or 'none'}")
    print(f"  in palcalc but not ours: {extra or 'none'}")
    print(f"  maxWild disagreements  : {clashes or 'none'}")
    if clashes:
        print("ABORT: the two dumps disagree on wild levels — resolve before shipping.")
        return 1

    body = []
    for name in sorted(facts):
        f = facts[name]
        mn = "null" if f["minWild"] is None else f["minWild"]
        mx = "null" if f["maxWild"] is None else f["maxWild"]
        extra = (
            f", passives: {json.dumps(f['passives'])}" if f["passives"] else ""
        )
        body.append(
            f"  {json.dumps(name)}: {{ rarity: {f['rarity']}, "
            f"minWild: {mn}, maxWild: {mx}{extra} }},"
        )

    text = HEADER.format(version=version, date="2026-08-15") + "\n".join(body) + "\n};\n"
    for out in OUT:
        out.write_text(text, encoding="utf-8")
        print(f"wrote {out.relative_to(ROOT)} ({len(facts)} pals)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
