#!/usr/bin/env python3
"""Per-species gender probabilities, datamined via palcalc's db.json
(BreedingGenderProbability — the game's own spawn-gender table).

Most species are 50/50; 44 are skewed (Beegarde 10% male, Kingpaca 90%
male, ...). Cake economics needs these: a step that must produce a MALE
Beegarde averages 10 eggs, not 1.

    python3 tools/extract_gender_ratio.py [path-to-db.json]

Fetches palcalc main's db.json when no path is given. Writes
mobile/src/data/genderRatio.g.ts + app/src/data/genderRatio.g.ts.
"""
import json
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = [
    ROOT / "mobile" / "src" / "data" / "genderRatio.g.ts",
    ROOT / "app" / "src" / "data" / "genderRatio.g.ts",
]
DB_URL = "https://raw.githubusercontent.com/tylercamp/palcalc/main/PalCalc.Model/db.json"


def main() -> int:
    if len(sys.argv) > 1:
        raw = Path(sys.argv[1]).read_text(encoding="utf-8")
    else:
        raw = urllib.request.urlopen(DB_URL).read().decode("utf-8")
    db = json.loads(raw)
    name_of = {p["InternalName"]: p["Name"] for p in db["Pals"]}
    ratios = db["BreedingGenderProbability"]

    # our dataset's names, to guarantee every key resolves
    ours = set(json.loads(
        (ROOT / "data" / "pals_1_0.json").read_text(encoding="utf-8"))["pals"])

    skewed: dict[str, float] = {}
    unmatched: list[str] = []
    for internal, v in ratios.items():
        name = name_of.get(internal, internal)
        if name not in ours:
            unmatched.append(name)
            continue
        male = v["MALE"]
        if abs(male - 0.5) > 0.001:
            skewed[name] = male
    print(f"palcalc {db['Version']}: {len(ratios)} species, "
          f"{len(skewed)} skewed, unmatched: {unmatched or 'none'}")

    lines = [
        "/** GENERATED by tools/extract_gender_ratio.py — DO NOT EDIT.",
        f" * Per-species male probability, datamined (palcalc {db['Version']}",
        " * BreedingGenderProbability — the game's own gender table). Only the",
        " * skewed species are listed; everything else is 50/50. */",
        "",
        "/** male probability for species NOT at 50/50 */",
        "export const MALE_PROB_SKEWED: Record<string, number> = {",
    ]
    for name in sorted(skewed):
        lines.append(f"  {json.dumps(name)}: {skewed[name]},")
    lines.append("};")
    lines.append("")
    lines.append("/** male probability for any species (default 0.5) */")
    lines.append("export const maleProb = (name: string): number =>")
    lines.append("  MALE_PROB_SKEWED[name] ?? 0.5;")
    text = "\n".join(lines) + "\n"

    for out in OUT:
        out.write_text(text, encoding="utf-8")
        print(f"wrote {out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
