#!/usr/bin/env python3
"""Generate mobile/src/data/regionSpots.g.ts — spawn-region label positions
as normalized coordinates on the game map image.

Sources:
- kb data/regions.json: paldb region-label positions in in-game map coords.
- palcalc GameConstants: WorldToMapMatrix (A) / WorldToImageMatrix (B), read
  from the game files. Image position = B @ inv(A) @ map_coord — the exact
  transform already validated by tools/extract_alpha_spots.py.

Run: python tools/extract_region_spots.py /path/to/kb-clone
"""
import json
import sys
from pathlib import Path

KB = Path(sys.argv[1] if len(sys.argv) > 1 else ".")
OUT = Path(__file__).resolve().parent.parent / "mobile" / "src" / "data" / "regionSpots.g.ts"

A = [
    [-4.830223727277094e-07, 0.0021796738568829717, -344.193826581459],
    [0.0021779338609583232, 1.3843765562632747e-06, 269.9073674619908],
    [0.0, 0.0, 1.0],
]
B = [
    [5.853358785966763e-10, 6.942623697264833e-07, 0.49957354110764096],
    [-6.900889463287533e-07, -3.9501572187562305e-10, 0.24117673696704256],
    [0.0, 0.0, 1.0],
]


def mat_inv3(m):
    a, b, c = m[0]
    d, e, f = m[1]
    g, h, i = m[2]
    det = a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)
    inv = [
        [(e * i - f * h) / det, (c * h - b * i) / det, (b * f - c * e) / det],
        [(f * g - d * i) / det, (a * i - c * g) / det, (c * d - a * f) / det],
        [(d * h - e * g) / det, (b * g - a * h) / det, (a * e - b * d) / det],
    ]
    return inv


def mat_mul_vec(m, v):
    return [sum(m[r][c] * v[c] for c in range(3)) for r in range(3)]


def map_to_image(mx, my):
    world = mat_mul_vec(mat_inv3(A), [mx, my, 1.0])
    img = mat_mul_vec(B, world)
    return img[0], img[1]


def main():
    data = json.loads((KB / "data" / "regions.json").read_text(encoding="utf-8"))
    regions = data["regions"]
    on_map = {}
    off_map = []
    for name, (mx, my) in sorted(regions.items()):
        if len(name.strip()) < 2:  # junk label in the source data
            continue
        x, y = map_to_image(mx, my)
        if 0.0 <= x <= 1.0 and 0.0 <= y <= 1.0:
            on_map[name] = (round(x, 4), round(y, 4))
        else:
            off_map.append(name)

    lines = [
        "/** GENERATED by tools/extract_region_spots.py — DO NOT EDIT.",
        " * Spawn-region label positions as fractions of the map image.",
        f" * Source: kb regions.json ({data.get('updated', '?')}), projected with the",
        " * game's own map transforms. Regions beyond the base map are omitted",
        f" * ({len(off_map)} off-map: {', '.join(off_map) if off_map else 'none'}). */",
        "export const REGION_SPOTS: Record<string, { x: number; y: number }> = {",
    ]
    for name, (x, y) in on_map.items():
        safe = name.replace("'", "\\'")
        lines.append(f"  '{safe}': {{ x: {x}, y: {y} }},")
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name}: {len(on_map)} on-map regions, {len(off_map)} off-map")


if __name__ == "__main__":
    main()
