#!/usr/bin/env python3
"""Mine utility roles from the game's own partner-skill text.

The CEO's suggestion-engine mandate (AI_TODO §C4) wants squads like "ore
weight reduction", "faster gathering", "gliders", "flying mounts" — and every
one of those is already sitting in pals_1_0.json as game text:

  * partner_effect — quoted verbatim per pal, classified by pattern
  * mount          — the dump's own ground / flying / swim field

So these squads need NO community source at all. Community tier lists are
only ever used (separately, labelled) for subjective "best overall" claims.

    python3 tools/extract_utility_roles.py

Writes mobile/src/data/utilityRoles.g.ts + app/src/data/utilityRoles.g.ts.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = [
    ROOT / "mobile" / "src" / "data" / "utilityRoles.g.ts",
    ROOT / "app" / "src" / "data" / "utilityRoles.g.ts",
]

# ordered: first match wins, so a mining-efficiency pal that also reduces
# stone weight files under efficiency (the stronger claim), with the full
# quote preserved either way
ROLES: list[tuple[str, str, re.Pattern]] = [
    ("efficiency", "Work efficiency boosters",
     re.compile(r"efficiency", re.I)),
    ("weight", "Weight & carrying helpers",
     re.compile(r"carry|weight", re.I)),
    ("drops", "Better drops & yields",
     re.compile(r"drop", re.I)),
    ("glider", "Glider pals",
     re.compile(r"glider", re.I)),
]


def main() -> int:
    pals = json.loads(
        (ROOT / "data" / "pals_1_0.json").read_text(encoding="utf-8"))["pals"]

    roles: dict[str, list[dict]] = {k: [] for k, _, _ in ROLES}
    for name in sorted(pals, key=lambda n: (
            int(re.sub(r"\D", "", pals[n]["number"] or "999") or 999), n)):
        effect = pals[name].get("partner_effect") or ""
        for key, _, rx in ROLES:
            if rx.search(effect):
                roles[key].append({"name": name, "effect": effect.strip()})
                break

    mounts: dict[str, list[str]] = {"flying": [], "ground": [], "swim": []}
    for name in sorted(pals, key=lambda n: (
            int(re.sub(r"\D", "", pals[n]["number"] or "999") or 999), n)):
        m = pals[name].get("mount")
        if m in mounts:
            mounts[m].append(name)

    counts = {k: len(v) for k, v in roles.items()}
    print("roles:", counts, "| mounts:",
          {k: len(v) for k, v in mounts.items()})

    lines = [
        "/** GENERATED by tools/extract_utility_roles.py — DO NOT EDIT.",
        " * Utility squads mined from the game's own partner-skill text and",
        " * mount field (pals_1_0.json). Every effect string is the game's,",
        " * verbatim — no community sourcing involved. */",
        "export interface UtilityPal { name: string; effect: string }",
        "",
        "export const UTILITY_ROLES: Record<string, { label: string; pals: UtilityPal[] }> = {",
    ]
    for key, label, _ in ROLES:
        lines.append(f"  {key}: {{")
        lines.append(f"    label: {json.dumps(label)},")
        lines.append("    pals: [")
        for e in roles[key]:
            lines.append(
                f"      {{ name: {json.dumps(e['name'])}, "
                f"effect: {json.dumps(e['effect'])} }},")
        lines.append("    ],")
        lines.append("  },")
    lines.append("};")
    lines.append("")
    lines.append("/** the dump's own mount typing — order is Paldex order; "
                 "speed claims need a labelled community source */")
    lines.append("export const MOUNTS: Record<'flying' | 'ground' | 'swim', string[]> = {")
    for k in ("flying", "ground", "swim"):
        lines.append(f"  {k}: {json.dumps(mounts[k])},")
    lines.append("};")
    text = "\n".join(lines) + "\n"

    for out in OUT:
        out.write_text(text, encoding="utf-8")
        print(f"wrote {out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
