#!/usr/bin/env python3
"""Fetch the GAME's own map symbols so our markers look like the game's.

The CEO's note, with an in-game screenshot: "All symbols should be same as game
use also." He is right — a generic pickaxe glyph where the game draws its own
ore symbol is the difference between "a map" and "the game's map".

Nifrendil/pal-atlas (MIT) bakes the game's UI icons out of the PAK into
public/icons/, and its names line up one-for-one with our 23 POI layers.

Run: python tools/fetch_map_icons.py
"""
from __future__ import annotations

import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = [ROOT / "mobile" / "assets" / "mapicons", ROOT / "app" / "public" / "mapicons"]
BASE = "https://raw.githubusercontent.com/Nifrendil/pal-atlas/main/public/icons"

# our layer id -> pal-atlas file name
ICONS = {
    "alpha_pals": "alpha-pals",
    "bounty_targets": "bounty-targets",
    "chest": "chest",
    "coal": "coal",
    "crude_oil": "crude-oil",
    "dungeon": "dungeon",
    "egg": "egg",
    "fast_travel": "fast-travel",
    "merchant": "merchant",
    "mushrooms": "mushrooms",
    "note": "note",
    "npc": "npc",
    "ore": "ore",
    "pal_effigy": "pal-effigy",
    "pal_merchant": "pal-merchant",
    "paldium": "paldium",
    "pure_quartz": "pure-quartz",
    "red_berries": "red-berries",
    "sealed_realm": "sealed-realm",
    "skill_fruit": "skill-fruit",
    "soralite": "soralite",
    "sulfur": "sulfur",
    "syndicate_tower": "syndicate-tower",
}


def main() -> None:
    for d in OUT:
        d.mkdir(parents=True, exist_ok=True)
    got = 0
    for layer, name in sorted(ICONS.items()):
        data = urllib.request.urlopen(f"{BASE}/{name}.png", timeout=30).read()
        for d in OUT:
            (d / f"{layer}.png").write_bytes(data)
        got += 1
        print(f"  {layer:<18} {len(data):>6} bytes")

    lines = [
        "/** GENERATED by tools/fetch_map_icons.py — DO NOT EDIT.",
        " * The GAME's own map symbols (Nifrendil/pal-atlas, MIT, baked from the",
        " * PAK). One per POI layer, so a marker on our map reads the same as the",
        " * marker the player already knows from the game. */",
        "/* eslint-disable @typescript-eslint/no-require-imports */",
        "",
        "export const MAP_ICONS: Record<string, number> = {",
    ]
    for layer in sorted(ICONS):
        lines.append(f"  {layer}: require('../../assets/mapicons/{layer}.png'),")
    lines += ["};", ""]
    (ROOT / "mobile" / "src" / "data" / "mapIcons.g.ts").write_text(
        "\n".join(lines), encoding="utf-8")

    web = [
        "/** GENERATED by tools/fetch_map_icons.py — DO NOT EDIT.",
        " * The game's own map symbols; the web app serves them from /mapicons/. */",
        f"export const MAP_ICON_LAYERS = new Set({sorted(ICONS)!r});".replace("'", "'"),
        "",
    ]
    (ROOT / "app" / "src" / "data" / "mapIcons.g.ts").write_text(
        "\n".join(web), encoding="utf-8")
    print(f"\n{got} game symbols written to both platforms")


if __name__ == "__main__":
    main()
