#!/usr/bin/env python3
"""Fetch every item's icon and pack them into sprite sheets.

The CEO's order (2026-08-18): "Everything needs a square for the image of
the item." 722 unique icon names cover the 1,892-item catalogue. They
CANNOT ship as individual files — EAS hard-caps 1000 assets per update
and the cap already broke publishing once — so they ship as a few big
sheets plus a generated coordinate map.

URL discovery is exact, never guessed: for each unique icon name, one
representative item's paldb page is fetched and its og:image meta tag
names the precise texture URL. Icons download once and are composed into
2048x2048 sheets of 96px cells (441 per sheet). Output:
  mobile/assets/itemicons/sheet0.png, sheet1.png ...
  mobile/src/data/itemIcons.g.ts   (icon name -> sheet/cell coordinates)

    python3 tools/fetch_item_icons.py
"""
import io
import json
import re
import time
import urllib.request
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / "tools" / ".cache" / "itemicons"
SHEET_DIR = ROOT / "mobile" / "assets" / "itemicons"
MAP_OUT = ROOT / "mobile" / "src" / "data" / "itemIcons.g.ts"
UA = "PalforgeDataPipeline/1.0 (companion app; contact: palandre.99@gmail.com)"
OG_IMG = re.compile(r'<meta property="og:image" content="([^"]+)"')
CELL = 96
PER_ROW = 21          # 21 * 96 = 2016 <= 2048
PER_SHEET = PER_ROW * PER_ROW


def slug_for(name: str) -> str:
    return (name.replace(" ", "_").replace("&", "%26").replace(",", "%2C")
            .replace("(", "%28").replace(")", "%29"))


def fetch(url: str, referer: bool = False) -> bytes | None:
    headers = {"User-Agent": UA}
    if referer:
        headers["Referer"] = "https://paldb.cc/"
    req = urllib.request.Request(url, headers=headers)
    for attempt in (1, 2):
        try:
            with urllib.request.urlopen(req, timeout=30) as r:
                return r.read()
        except Exception:  # noqa: BLE001
            if attempt == 2:
                return None
            time.sleep(2)
    return None


def main() -> None:
    CACHE.mkdir(parents=True, exist_ok=True)
    SHEET_DIR.mkdir(parents=True, exist_ok=True)
    items = json.loads(
        (ROOT / "data" / "items_1_0.json").read_text(encoding="utf-8"))["items"]

    # one representative item per unique icon name
    rep: dict[str, str] = {}
    for iid, it in items.items():
        if it.get("icon") and it["icon"] not in rep:
            rep[it["icon"]] = it["name"]
    print(f"{len(rep)} unique icons to resolve", flush=True)

    resolved: dict[str, Path] = {}
    misses: list[str] = []
    for i, (icon, name) in enumerate(sorted(rep.items()), 1):
        out = CACHE / f"{icon}.webp"
        if out.exists():
            resolved[icon] = out
            continue
        page = fetch(f"https://paldb.cc/en/{slug_for(name)}")
        url = None
        if page is not None:
            m = OG_IMG.search(page.decode("utf-8", "replace"))
            if m and "itemicon" in m.group(1).lower():
                url = m.group(1)
        if url:
            img = fetch(url, referer=True)
            if img:
                out.write_bytes(img)
                resolved[icon] = out
        if icon not in resolved:
            misses.append(icon)
        if i % 50 == 0:
            print(f"  {i}/{len(rep)} ({len(misses)} misses)", flush=True)
        time.sleep(0.6)

    print(f"resolved {len(resolved)}, missed {len(misses)}", flush=True)

    # compose sheets — deterministic order so reruns are stable
    order = sorted(resolved)
    coords: dict[str, tuple[int, int, int]] = {}
    sheets: list[Image.Image] = []
    for idx, icon in enumerate(order):
        sheet_i, cell_i = divmod(idx, PER_SHEET)
        while len(sheets) <= sheet_i:
            sheets.append(Image.new("RGBA", (PER_ROW * CELL, PER_ROW * CELL), (0, 0, 0, 0)))
        row, col = divmod(cell_i, PER_ROW)
        try:
            img = Image.open(io.BytesIO(resolved[icon].read_bytes())).convert("RGBA")
        except Exception:  # noqa: BLE001 - unreadable file -> treat as miss
            misses.append(icon)
            continue
        img.thumbnail((CELL, CELL), Image.LANCZOS)
        dx = col * CELL + (CELL - img.width) // 2
        dy = row * CELL + (CELL - img.height) // 2
        sheets[sheet_i].paste(img, (dx, dy))
        coords[icon] = (sheet_i, col, row)

    for i, sheet in enumerate(sheets):
        p = SHEET_DIR / f"sheet{i}.png"
        sheet.save(p, optimize=True)
        print(f"wrote {p} ({p.stat().st_size // 1024} KB)", flush=True)

    lines = [
        "/** GENERATED by tools/fetch_item_icons.py — DO NOT EDIT.",
        " *",
        " * Item icons packed into sprite sheets (96px cells, 21 per row) —",
        " * individual files would trip EAS's 1000-asset cap. Each entry is",
        " * [sheet, column, row]; URLs were resolved from each item page's",
        " * own og:image tag, never guessed. Missing icons simply have no",
        " * entry and the UI shows its designed placeholder. */",
        "",
        "/* eslint-disable @typescript-eslint/no-require-imports */",
        f"export const ICON_CELL = {CELL};",
        f"export const ICONS_PER_ROW = {PER_ROW};",
        "export const ITEM_ICON_SHEETS: number[] = [",
        *(f"  require('../../assets/itemicons/sheet{i}.png')," for i in range(len(sheets))),
        "];",
        "export const ITEM_ICON_COORDS: Record<string, [number, number, number]> = "
        + json.dumps({k: list(v) for k, v in coords.items()}, separators=(",", ":"))
        + ";",
        "",
    ]
    MAP_OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {MAP_OUT} ({len(coords)} icons on {len(sheets)} sheets); "
          f"{len(set(misses))} missing: {sorted(set(misses))[:10]}", flush=True)


if __name__ == "__main__":
    main()
