#!/usr/bin/env python3
"""Keep every species' portrait bundled, and rebuild the require map.

WHY THIS EXISTS: the icon map said it was "GENERATED by scripts in
package.json" and no such script existed anywhere in the repo, so the
298 portraits had been gathered by hand. The 299th species (Astralym,
the World Tree boss) had no portrait at all, and its rows drew initials
in a grey circle — found by the Bosses fane's tower list, where Astralym
is the final fight. A hand process cannot survive a patch that adds
pals; this can.

WHAT IT DOES: reads pals_1_0.json, works out each species' asset name
from the icon URL the data already carries (T_DomeArmorDragon_icon_
normal.webp -> DomeArmorDragon.png — the convention the existing 298
follow), downloads anything missing, converts to PNG, and rewrites
mobile/src/data/icons.g.ts from what is actually on disk.

It never invents a portrait: a species whose icon URL is absent or
unreachable is reported and simply stays out of the map, where the app's
initials fallback already handles it.

    python3 tools/fetch_pal_icons.py
"""
import json
import re
import sys
import urllib.request
from io import BytesIO
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
PALS = ROOT / "data" / "pals_1_0.json"
ICONS = ROOT / "mobile" / "assets" / "icons"
OUT = ROOT / "mobile" / "src" / "data" / "icons.g.ts"
# the image CDN refuses a bare tool UA (403) but serves the same file to a
# normal browser request — same source, same bytes, just headers it accepts
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "PalforgeDataPipeline/1.0 (companion app; "
                  "contact: palandre.99@gmail.com)",
    "Referer": "https://paldb.cc/",
}


def asset_name(icon_url: str) -> str | None:
    """T_<Code>_icon_normal.webp -> <Code> (the shipped convention)."""
    m = re.search(r"/T_(.+?)_icon_normal\.webp", icon_url or "")
    return m.group(1) if m else None


def main() -> None:
    pals = json.loads(PALS.read_text(encoding="utf-8"))["pals"]
    fetched, missing, skipped = [], [], []
    mapping: dict[str, str] = {}

    for name, p in sorted(pals.items()):
        code = asset_name(p.get("icon") or "")
        if code is None:
            missing.append(f"{name}: no icon URL in the data")
            continue
        png = ICONS / f"{code}.png"
        if not png.exists():
            req = urllib.request.Request(p["icon"], headers=HEADERS)
            try:
                with urllib.request.urlopen(req, timeout=30) as r:
                    raw = r.read()
                img = Image.open(BytesIO(raw)).convert("RGBA")
                img.save(png, "PNG")
                fetched.append(f"{name} -> {png.name} ({img.width}x{img.height})")
            except Exception as ex:  # noqa: BLE001 - report, never guess
                missing.append(f"{name}: {ex}")
                continue
        mapping[name] = code

    # rebuild the map from what is really on disk, so a deleted asset can
    # never leave a require() pointing at nothing
    for name in list(mapping):
        if not (ICONS / f"{mapping[name]}.png").exists():
            skipped.append(name)
            del mapping[name]

    lines = [
        "/** GENERATED by tools/fetch_pal_icons.py — do not edit.",
        " *",
        " * Static require map: Metro needs literal paths, so every",
        " * portrait is listed. Rerun the tool after a game patch adds",
        " * species; it downloads what is missing and rewrites this file",
        " * from the assets actually on disk.",
        " */",
        "/* eslint-disable @typescript-eslint/no-require-imports */",
        "export const PAL_ICONS: Record<string, number> = {",
    ]
    for name, code in sorted(mapping.items()):
        lines.append(f"  {json.dumps(name)}: require('../../assets/icons/{code}.png'),")
    lines += ["};", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")

    print(f"portraits mapped: {len(mapping)} of {len(pals)} species")
    for f in fetched:
        print(f"  FETCHED {f}")
    for m in missing:
        print(f"  MISSING {m}")
    for s in skipped:
        print(f"  DROPPED (asset gone) {s}")
    if len(mapping) < len(pals):
        print(f"note: {len(pals) - len(mapping)} species keep the initials "
              "fallback — nothing invented")


if __name__ == "__main__":
    sys.exit(main())
