#!/usr/bin/env python3
"""Fetch each mount's saddle technology level from paldb.cc.

The CEO wants mounts to say "saddle available Lv X" (AI_TODO §C6b). The kb
dump carries no saddle tech data (verified 2026-08-15), but every paldb pal
page shows the unlock item in the Partner Skill section:

    <a ... href="Direhowls_Saddled_Harness"><img ...SkillUnlock_Saddle...>
    ... <span ...>Technology</span><span class="border p-1">9</span>

Only pals with a `mount` type in pals_1_0.json are fetched (121 of 299).
Pals whose partner skill needs no saddle item (or where the pattern is
absent) are recorded as null — the UI just says nothing for them.

    python3 tools/fetch_saddle_levels.py

Writes mobile/src/data/saddleLevels.g.ts + app/src/data/saddleLevels.g.ts.
"""
import json
import re
import time
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = [
    ROOT / "mobile" / "src" / "data" / "saddleLevels.g.ts",
    ROOT / "app" / "src" / "data" / "saddleLevels.g.ts",
]
UA = "PalforgeDataPipeline/1.0 (companion app; contact: palandre.99@gmail.com)"

# the unlock icon anchors the match; the FIRST Technology level after it is
# the saddle's (later ones on the page belong to other tech items)
SADDLE_RE = re.compile(
    r"SkillUnlock[^\n]*?Technology</span><span[^>]*>(\d+)</span>", re.S)


def fetch(name: str) -> int | None:
    slug = name.replace(" ", "_")
    req = urllib.request.Request(
        f"https://paldb.cc/en/{slug}", headers={"User-Agent": UA})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            page = r.read().decode("utf-8", "replace")
    except Exception as e:  # noqa: BLE001
        print(f"{name}: fetch failed ({e})")
        return None
    m = SADDLE_RE.search(page)
    return int(m.group(1)) if m else None


def main() -> int:
    pals = json.loads(
        (ROOT / "data" / "pals_1_0.json").read_text(encoding="utf-8"))["pals"]
    mounts = sorted(n for n in pals if pals[n].get("mount"))
    print(f"fetching saddle levels for {len(mounts)} mounts")

    levels: dict[str, int | None] = {}
    for name in mounts:
        lv = fetch(name)
        levels[name] = lv
        print(f"  {name}: {'Lv ' + str(lv) if lv else 'none found'}")
        time.sleep(1.1)  # be a polite guest

    found = sum(1 for v in levels.values() if v)
    lines = [
        "/** GENERATED by tools/fetch_saddle_levels.py — DO NOT EDIT.",
        " * Saddle/harness technology unlock level per mount, from each pal's",
        " * paldb.cc page (fetched " + time.strftime("%Y-%m-%d") + "; "
        + f"{found}/{len(levels)} mounts have one).",
        " * null = no saddle item found (some partner skills need none). */",
        "export const SADDLE_LEVELS: Record<string, number | null> = {",
    ]
    for name in mounts:
        v = levels[name]
        lines.append(f"  {json.dumps(name)}: {v if v is not None else 'null'},")
    lines.append("};")
    text = "\n".join(lines) + "\n"
    for out in OUT:
        out.write_text(text, encoding="utf-8")
        print(f"wrote {out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
