#!/usr/bin/env python3
"""Generate the tower/raid encounter tables for both trees.

Reads data/tower_raid_1_0.json (tools/fetch_tower_raid_stats.py — every
row validated: section Code == list id, elements agree between the two
paldb renderings, skills mapped into our nine elements) and writes an
identical towerRaid.g.ts into BOTH mobile/src/data/ and app/src/data/,
because the counters logic and its tests are parity modules.

    python3 tools/gen_tower_raid.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "tower_raid_1_0.json"
OUTS = [
    ROOT / "mobile" / "src" / "data" / "towerRaid.g.ts",
    ROOT / "app" / "src" / "data" / "towerRaid.g.ts",
]


def ts_str(v) -> str:
    if v is None:
        return "null"
    return json.dumps(str(v))


def ts_num(v) -> str:
    if v in (None, ""):
        return "null"
    return str(float(v)).rstrip("0").rstrip(".") or "0"


def encounter(row: dict) -> str:
    moves = ", ".join(
        "{ lv: %d, name: %s, element: %s, ct: %d, power: %d, effects: %s }"
        % (m["lv"], json.dumps(m["name"]), json.dumps(m["element"]),
           m["ct"], m["power"], json.dumps(m["effects"]))
        for m in row["moves"])
    drops = ", ".join(
        "{ item: %s, qty: %s, pct: %s }"
        % (json.dumps(d["item"]), json.dumps(d["qty"]), d["pct"])
        for d in row.get("drops", []))
    title = re.sub(r"\s+", " ", row["title"]).strip()
    els = ", ".join(json.dumps(e) for e in row["elements"])
    return (
        "  {\n"
        f"    title: {json.dumps(title)},\n"
        f"    arena: {ts_str(row['arena'])},\n"
        f"    mode: {json.dumps(row['mode'])},\n"
        f"    lv: {ts_num(row['lv'])},\n"
        f"    fightHp: {ts_num(row['fightHp'])},\n"
        f"    damageCutPct: {ts_num(row['damageCutPct'])},\n"
        f"    attackPct: {ts_num(row['attackPct'])},\n"
        f"    slab: {ts_str(row['slab'])},\n"
        f"    bp: {json.dumps(row['bp'])},\n"
        f"    species: {ts_str(row['species'])},\n"
        f"    elements: [{els}],\n"
        f"    towerFlag: {'true' if row.get('towerFlag') else 'false'},\n"
        f"    raidFlag: {'true' if row.get('raidFlag') else 'false'},\n"
        f"    size: {ts_str(row['size'])},\n"
        f"    hpRate: {ts_num(row['hpRate'])},\n"
        f"    recvRate: {ts_num(row['recvRate'])},\n"
        f"    dealRate: {ts_num(row['dealRate'])},\n"
        f"    ctRate: {ts_num(row['ctRate'])},\n"
        f"    genus: {ts_str(row['genus'])},\n"
        f"    moves: [{moves}],\n"
        f"    drops: [{drops}],\n"
        "  },"
    )


def main() -> None:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    towers = "\n".join(encounter(r) for r in data["towers"])
    raids = "\n".join(encounter(r) for r in data["raids"])
    src_line = json.dumps(data["source"])

    ts = f"""/** GENERATED by tools/gen_tower_raid.py — do not edit.
 *
 * Every tower-boss and summoned-raid encounter, per difficulty, from the
 * game's own parameter rows as mirrored by paldb.cc. Validation and
 * provenance in data/tower_raid_1_0.json (counts, refusals, notes).
 *
 * fightHp is the HP bar the player actually faces in that fight at that
 * difficulty. damageCutPct / attackPct exist for raids only (the raid
 * table publishes them; the tower table does not). elements can be empty:
 * Zenara & Astralym and Moon Lord genuinely have no element on their raw
 * rows — no element is strong or weak against them. moves is the boss
 * variant's OWN attack list at that difficulty (Hard kits really differ:
 * Zoe & Grizzbolt Normal has 5 attacks, Hard has 9). towerFlag/raidFlag
 * are the raw row's own IsTowerBoss/IsRaidBoss — the three Lv-78
 * story-dungeon fights on the tower list carry towerFlag: false.
 */

export interface BossMove {{
  lv: number;
  name: string;
  element: string;
  /** seconds between uses, before the boss's own cooldown multiplier */
  ct: number;
  power: number;
  effects: string | null;
}}

export interface BossDrop {{
  /** the game's own item name; a few are absent from the items index
   * (the tower Key Spheres) — reported by the fetch, shown regardless */
  item: string;
  /** "1" or a range like "1-3", exactly as the table states it */
  qty: string;
  pct: number;
}}

export interface BossEncounter {{
  title: string;
  arena: string | null;
  mode: 'Normal' | 'Hard' | 'Ultra' | 'Master';
  lv: number;
  fightHp: number;
  damageCutPct: number | null;
  attackPct: number | null;
  /** summoning slab item code (raids only) */
  slab: string | null;
  bp: string;
  /** our Paldex species this boss is, when it is one */
  species: string | null;
  elements: string[];
  towerFlag: boolean;
  raidFlag: boolean;
  size: string | null;
  hpRate: number | null;
  recvRate: number | null;
  dealRate: number | null;
  ctRate: number | null;
  genus: string | null;
  moves: BossMove[];
  /** what beating THIS difficulty gives you, with the game's own odds */
  drops: BossDrop[];
}}

export const TOWER_RAID_SOURCE = {src_line};

export const TOWER_BOSSES: BossEncounter[] = [
{towers}
];

export const RAID_BOSSES: BossEncounter[] = [
{raids}
];
"""
    for out in OUTS:
        out.write_text(ts, encoding="utf-8", newline="\n")
        print(f"wrote {out}")


if __name__ == "__main__":
    main()
