#!/usr/bin/env python3
"""Generate the element-chart table for both trees from the fetched JSON.

Reads data/elements_1_0.json (tools/fetch_element_chart.py — two wikis in
cell-for-cell agreement, antisymmetry proven, vocabulary equal to
pals_1_0.json) and writes an identical elementChart.g.ts into BOTH
mobile/src/data/ and app/src/data/, because src/logic/counters.ts is a
byte-parity module and its data import has to resolve in each tree.

The file name is elementChart.g.ts, NOT elements.ts — that name is taken
by the Paldex-order filter list and means something else.

    python3 tools/gen_element_chart.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "elements_1_0.json"
OUTS = [
    ROOT / "mobile" / "src" / "data" / "elementChart.g.ts",
    ROOT / "app" / "src" / "data" / "elementChart.g.ts",
]


def main() -> None:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    rows = []
    for el in sorted(data["elements"]):
        row = data["elements"][el]
        strong = ", ".join(f"'{s}'" for s in row["strong"])
        weak = ", ".join(f"'{s}'" for s in row["weak"])
        rows.append(f"  {el}: {{ strong: [{strong}], weak: [{weak}] }},")
    body = "\n".join(rows)

    src_line = json.dumps(data["source"])
    ts = f"""/** GENERATED by tools/gen_element_chart.py — do not edit.
 *
 * The game's element strengths chart. Wiki-measured, not datamined —
 * accepted only because two independent wikis agree cell-for-cell, the
 * table is perfectly antisymmetric, and its vocabulary equals our pals
 * data exactly. Provenance (both revision ids) in data/elements_1_0.json.
 *
 * Reading it: an attack of element A deals double to every element in
 * chart[A].strong and half to every element in chart[A].weak; per-element
 * multipliers on a dual-element pal multiply, so strong+weak cancels to
 * even. A skill matching the defender's own element is even too. No pal
 * in our data takes 4x or 0.25x (counted at generation time, 299 pals).
 */

export interface ElementMatchups {{
  strong: string[];
  weak: string[];
}}

export const ELEMENT_CHART_SOURCE = {src_line};

export const ELEMENT_CHART: Record<string, ElementMatchups> = {{
{body}
}};
"""
    for out in OUTS:
        out.write_text(ts, encoding="utf-8", newline="\n")
        print(f"wrote {out}")


if __name__ == "__main__":
    main()
