#!/usr/bin/env python3
"""Generate the app's compact fixed-boss stat table from the fetched rows.

Reads data/alpha_stats_1_0.json (tools/fetch_alpha_stats.py) and writes
mobile/src/data/alphaStats.g.ts with only what the card renders: the boss
row's own combat numbers next to nothing it doesn't need. Every value is
the game's own DT_PalMonsterParameter figure via paldb (validated per row
against our CombiRank before it ever reached the JSON).

    python3 tools/gen_alpha_stats.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "alpha_stats_1_0.json"
OUT = ROOT / "mobile" / "src" / "data" / "alphaStats.g.ts"


def num(row: dict, key: str) -> float | None:
    v = row.get(key)
    if v is None:
        return None
    try:
        return float(v)
    except ValueError:
        return None


def main() -> None:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    pals = json.loads(
        (ROOT / "data" / "pals_1_0.json").read_text(encoding="utf-8"))["pals"]

    out: dict[str, list[dict]] = {}
    for name, rows in sorted(data["bosses"].items()):
        if name not in pals:
            raise SystemExit(f"unknown species in alpha stats: {name}")
        entries = []
        for r in rows:
            entry = {
                "title": r["title"],
                "lv": r.get("lv"),
                "hp": num(r, "hp"),
                "atk": num(r, "atk"),
                "def": num(r, "def"),
                "size": r.get("size") or None,
                "hpRate": num(r, "hpRate"),
                "recvRate": num(r, "recvRate"),
                "capture": num(r, "capture"),
            }
            if entry["hp"] is None:
                continue  # a row with no combat stats has nothing to show
            entries.append(entry)
        if entries:
            out[name] = entries

    lines = [
        "/** GENERATED by tools/gen_alpha_stats.py — DO NOT EDIT.",
        " *",
        " * The fixed boss's own row from the game's DT_PalMonsterParameter,",
        " * one entry per named boss, via paldb.cc (fetched 2026-08-18).",
        " * Every row was validated against our oracle-tested CombiRank",
        " * before it was accepted; see data/alpha_stats_1_0.json for the",
        " * full capture and the drop list. */",
        "",
        "export interface AlphaStat {",
        "  /** the game's own boss title, e.g. \"Big Floof Lamball\" */",
        "  title: string;",
        "  /** the boss's level at its spot */",
        "  lv: number | null;",
        "  /** the boss row's own base stats */",
        "  hp: number; atk: number | null; def: number | null;",
        "  size: string | null;",
        "  /** fight multipliers from the same row: effective-HP scale and",
        "   * the fraction of your damage it actually takes */",
        "  hpRate: number | null; recvRate: number | null;",
        "  /** catch-chance multiplier */",
        "  capture: number | null;",
        "}",
        "",
        "export const ALPHA_STATS: Record<string, AlphaStat[]> = "
        + json.dumps(out, indent=1, ensure_ascii=False) + ";",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    total = sum(len(v) for v in out.values())
    print(f"wrote {OUT} ({len(out)} species, {total} boss rows)")


if __name__ == "__main__":
    main()
