"""What changed in the shipped item data, generated by comparing two builds.

The blueprint's criterion 14 asks for an in-app news row: "data updated
for build X — what changed", within days of every patch. Nothing in the
app has ever said it, because nothing ever WORKED OUT what changed.

This does, by diffing the item facts we are about to ship against the
ones we shipped last. It invents nothing: every line it emits is the
difference between two files we hold.

    # against whatever is committed now (the usual patch-day run)
    git show HEAD:palworld-breeding/data/item_facts_1_0.json > prev.json
    python tools/gen_data_changes.py --previous prev.json

Writes mobile/src/data/dataChanges.g.ts. Run it AFTER gen_item_facts.py,
with `--previous` pointing at the facts from before that run.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CURRENT = ROOT / "data" / "item_facts_1_0.json"
ITEMS = ROOT / "data" / "items_1_0.json"
OUT = ROOT / "mobile" / "src" / "data" / "dataChanges.g.ts"

# The fact keys worth telling a player about. Anything else that moves is
# counted but not named — "12 recipes changed" is news; a reordered list
# of chest names is not.
WATCHED = ["recipe", "tech", "craftWork", "craftTime", "capture", "effects",
           "grants", "drops", "boxes", "shops", "passives"]


def load(p: Path) -> dict:
    return json.loads(p.read_text(encoding="utf-8"))


def facts_of(payload: dict) -> dict:
    return payload.get("facts", payload)


def summarise(prev: dict, cur: dict, names: dict) -> dict:
    pf, cf = facts_of(prev), facts_of(cur)
    added = sorted(set(cf) - set(pf))
    removed = sorted(set(pf) - set(cf))
    changed: dict[str, list[str]] = {}
    for iid in sorted(set(pf) & set(cf)):
        moved = [k for k in WATCHED
                 if json.dumps(pf[iid].get(k), sort_keys=True)
                 != json.dumps(cf[iid].get(k), sort_keys=True)]
        if moved:
            changed[iid] = moved
    # group the changes by WHAT moved, which is how a player reads it
    by_key: dict[str, list[str]] = {}
    for iid, keys in changed.items():
        for k in keys:
            by_key.setdefault(k, []).append(names.get(iid, iid))
    for k in by_key:
        by_key[k] = sorted(set(by_key[k]))
    # five tiers of one weapon share one name — say it once, or the line
    # reads "Grappling Gun, Grappling Gun, Grappling Gun..."
    def spoken(ids: list[str]) -> list[str]:
        seen: list[str] = []
        for i in ids:
            n = names.get(i, i)
            if n not in seen:
                seen.append(n)
        return seen

    return {
        # names are deduped for reading; the COUNTS stay the real item
        # counts, so "5 items ... Grappling Gun" means five tiers of it
        "added": spoken(added), "addedCount": len(added),
        "removed": spoken(removed), "removedCount": len(removed),
        "byKey": by_key,
        "changedCount": len(changed),
    }


# The game's own words for each fact key — never the key itself.
KEY_WORDS = {
    "recipe": "recipes", "tech": "technology levels",
    "craftWork": "crafting work", "craftTime": "crafting times",
    "capture": "capture power", "effects": "effects",
    "grants": "what they grant", "drops": "drop tables",
    "boxes": "chest tables", "shops": "merchants",
    "passives": "equipment passives",
}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--previous", required=True,
                    help="the item_facts json from BEFORE this refresh")
    ap.add_argument("--label", default=None,
                    help="what this refresh was, in the CEO's words")
    args = ap.parse_args()

    prev = load(Path(args.previous))
    cur = load(CURRENT)
    names = {i: v["name"] for i, v in load(ITEMS)["items"].items()}
    s = summarise(prev, cur, names)

    lines: list[str] = []
    if s["added"]:
        lines.append(f"{s['addedCount']} items gained facts they had none of"
                     f" — {', '.join(s['added'][:6])}"
                     + (f" and {len(s['added']) - 6} more" if len(s["added"]) > 6 else ""))
    if s["removed"]:
        lines.append(f"{s['removedCount']} items lost their facts"
                     f" — {', '.join(s['removed'][:6])}")
    for key, who in sorted(s["byKey"].items(), key=lambda kv: -len(kv[1])):
        word = KEY_WORDS.get(key, key)
        head = ", ".join(who[:4])
        more = f" and {len(who) - 4} more" if len(who) > 4 else ""
        lines.append(f"{len(who)} {word} changed — {head}{more}")

    payload = {
        "when": dt.date.today().isoformat(),
        "label": args.label or "",
        "lines": lines,
        "itemsAdded": s["addedCount"],
        "itemsRemoved": s["removedCount"],
        "itemsChanged": s["changedCount"],
    }
    OUT.write_text(
        "/** GENERATED by tools/gen_data_changes.py — DO NOT EDIT.\n"
        " * What moved between the last shipped item data and this one.\n"
        " * Every line is the difference between two files we hold; nothing\n"
        " * here is written by hand. */\n"
        "export interface DataChange {\n"
        "  /** the day the refresh was generated */\n  when: string;\n"
        "  /** what the refresh was, in a player's words */\n  label: string;\n"
        "  /** one line per kind of change, biggest first */\n  lines: string[];\n"
        "  itemsAdded: number;\n  itemsRemoved: number;\n  itemsChanged: number;\n"
        "}\n\n"
        f"export const DATA_CHANGES: DataChange = {json.dumps(payload, indent=1, ensure_ascii=False)};\n",
        encoding="utf-8")
    print(f"wrote {OUT.name}: {len(lines)} lines, "
          f"{payload['itemsAdded']} added, {payload['itemsChanged']} changed")
    for ln in lines:
        print("  ·", ln)


if __name__ == "__main__":
    main()
