#!/usr/bin/env node
/** Generates dist/sw.js after `vite build`.
 *
 * The precache list is built from what is actually in dist/ (hashed assets,
 * data files, fonts, manifest, PWA icons) and the cache version is a sha256
 * over the FULL content of every listed file (plus index.html) — any byte
 * changing anywhere activates a fresh cache on the next visit, unchanged
 * deploys reuse the old one.
 *
 * Pal icons (public/icons/, ~6 MB) are NOT precached: they load cache-first
 * at runtime, so the pals you have seen work offline and first paint stays
 * light. Everything the app needs to function is precached.
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist');

/** walk dist/, skipping the icon set and the single-file bundle */
function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) {
      if (name === 'icons') continue;
      out.push(...walk(p));
    } else {
      // index.html is cached as '.' — caching it twice risks a redirected
      // response for the file URL on hosts that 308 /index.html -> /
      if (name === 'sw.js' || name === 'HatchLab-app.html' || name === 'index.html') continue;
      out.push(p);
    }
  }
  return out;
}

// FULL content hash. The data files keep stable names across deploys, so the
// cache version is the ONLY thing that gets updated data to existing users —
// a partial hash here would strand installed users on stale data forever.
const files = walk(dist).map((p) => relative(dist, p).replace(/\\/g, '/')).sort();
const hash = createHash('sha256');
for (const f of [...files, 'index.html']) {
  hash.update(f);
  hash.update(readFileSync(join(dist, f)));
}
const version = hash.digest('hex').slice(0, 12);

const sw = `/* HatchLab service worker — generated by scripts/build-sw.mjs, do not edit. */
const VERSION = '${version}';
const SHELL = 'hatchlab-shell-' + VERSION;
const ICONS = 'hatchlab-icons-v1'; // survives shell updates; icons rarely change
const PRECACHE = ${JSON.stringify(['.', ...files], null, 0)};

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(SHELL).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) => Promise.all(
      keys.filter((k) => k.startsWith('hatchlab-shell-') && k !== SHELL)
        .map((k) => caches.delete(k)),
    )).then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET' || url.origin !== location.origin) return;

  // pal icons: cache-first in their own long-lived cache
  if (url.pathname.includes('/icons/')) {
    e.respondWith(
      caches.open(ICONS).then((c) =>
        c.match(e.request).then((hit) => hit || fetch(e.request).then((res) => {
          if (res.ok) c.put(e.request, res.clone());
          return res;
        })),
      ),
    );
    return;
  }

  // shell + data: cache-first from the versioned precache, network fallback.
  // ignoreSearch only for navigations (so '/?utm=x' hits the shell) — asset
  // and data URLs keep their query strings meaningful for cache busting.
  e.respondWith(
    caches.match(e.request, { ignoreSearch: e.request.mode === 'navigate' }).then((hit) => {
      if (hit) return hit;
      return fetch(e.request).catch(() => {
        // offline navigation to a deep link -> serve the app shell ('.', the
        // scope root — never 'index.html', which some hosts 308-redirect)
        if (e.request.mode === 'navigate') return caches.match('.');
        return Response.error();
      });
    }),
  );
});
`;

writeFileSync(join(dist, 'sw.js'), sw);
console.log(`wrote dist/sw.js (cache ${version}, ${files.length} precached files)`);
