/* HatchLab service worker — generated by scripts/build-sw.mjs, do not edit. */
const VERSION = 'a841c6eac112';
const SHELL = 'hatchlab-shell-' + VERSION;
const ICONS = 'hatchlab-icons-v1'; // survives shell updates; icons rarely change
const PRECACHE = [".","assets/baloo2-sub-DgjrecBZ.woff2","assets/index-DB8l9uu_.js","assets/index-DOoZqeG1.css","assets/manrope-sub-CgxcFmsQ.woff2","assets/planner.worker-DwiVeJQx.js","data/breeding_1_0.json","data/icon_map.json","data/pals_1_0.json","data/passives_1_0.json","data/verification.json","favicon.svg","icon-192.png","icon-512.png","icon-maskable-512.png","icons.svg","manifest.webmanifest","work/Cooling.png","work/ElectricityGeneration.png","work/Farming.png","work/Gathering.png","work/Handiwork.png","work/Kindling.png","work/Lumbering.png","work/MedicineProduction.png","work/Mining.png","work/Planting.png","work/Transporting.png","work/Watering.png"];

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(SHELL).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) => Promise.all(
      keys.filter((k) => k.startsWith('hatchlab-shell-') && k !== SHELL)
        .map((k) => caches.delete(k)),
    )).then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET' || url.origin !== location.origin) return;

  // pal icons: cache-first in their own long-lived cache
  if (url.pathname.includes('/icons/')) {
    e.respondWith(
      caches.open(ICONS).then((c) =>
        c.match(e.request).then((hit) => hit || fetch(e.request).then((res) => {
          if (res.ok) c.put(e.request, res.clone());
          return res;
        })),
      ),
    );
    return;
  }

  // shell + data: cache-first from the versioned precache, network fallback.
  // ignoreSearch only for navigations (so '/?utm=x' hits the shell) — asset
  // and data URLs keep their query strings meaningful for cache busting.
  e.respondWith(
    caches.match(e.request, { ignoreSearch: e.request.mode === 'navigate' }).then((hit) => {
      if (hit) return hit;
      return fetch(e.request).catch(() => {
        // offline navigation to a deep link -> serve the app shell ('.', the
        // scope root — never 'index.html', which some hosts 308-redirect)
        if (e.request.mode === 'navigate') return caches.match('.');
        return Response.error();
      });
    }),
  );
});
