/** GENERATED by tools/gen_alpha_stats.py — DO NOT EDIT.
 *
 * The fixed boss's own row from the game's DT_PalMonsterParameter,
 * one entry per named boss, via paldb.cc (fetched 2026-08-18).
 * Every row was validated against our oracle-tested CombiRank
 * before it was accepted; see data/alpha_stats_1_0.json for the
 * full capture and the drop list. */

export interface AlphaStat {
  /** the game's own boss title, e.g. "Big Floof Lamball" */
  title: string;
  /** the boss's level at its spot */
  lv: number | null;
  /** the boss row's own base stats */
  hp: number; atk: number | null; def: number | null;
  size: string | null;
  /** fight multipliers from the same row: effective-HP scale and
   * the fraction of your damage it actually takes */
  hpRate: number | null; recvRate: number | null;
  /** catch-chance multiplier */
  capture: number | null;
}

export const ALPHA_STATS: Record<string, AlphaStat[]> = {
 "Aegidron": [
  {
   "title": "Guardian of Luminous Trails Aegidron",
   "lv": 79,
   "hp": 126.0,
   "atk": 125.0,
   "def": 140.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Anubis": [
  {
   "title": "Guardian of the Dark Sun Anubis",
   "lv": 55,
   "hp": 144.0,
   "atk": 130.0,
   "def": 100.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Arsox": [
  {
   "title": "Blazing Brute Arsox",
   "lv": 15,
   "hp": 102.0,
   "atk": 95.0,
   "def": 95.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Astegon": [
  {
   "title": "Draconic Monarch of Steel Astegon",
   "lv": 55,
   "hp": 120.0,
   "atk": 125.0,
   "def": 125.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Azurmane": [
  {
   "title": "Blue Lightning Steed Azurmane",
   "lv": 57,
   "hp": 156.0,
   "atk": 120.0,
   "def": 110.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Azurobe": [
  {
   "title": "Lady of the Lake Azurobe",
   "lv": 40,
   "hp": 132.0,
   "atk": 100.0,
   "def": 100.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Beakon": [
  {
   "title": "Wings of Thunderbolt Beakon",
   "lv": 37,
   "hp": 126.0,
   "atk": 115.0,
   "def": 80.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Blazamut": [
  {
   "title": "Cursed Tyrant Blazamut",
   "lv": 52,
   "hp": 120.0,
   "atk": 125.0,
   "def": 120.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Blazehowl": [
  {
   "title": "Crimson Goliath Blazehowl",
   "lv": 30,
   "hp": 126.0,
   "atk": 110.0,
   "def": 80.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Blazehowl Noct": [
  {
   "title": "Inferno Goliath Blazehowl Noct",
   "lv": 36,
   "hp": 126.0,
   "atk": 115.0,
   "def": 80.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Braloha": [
  {
   "title": "Ancient Bloombringer Braloha",
   "lv": 47,
   "hp": 156.0,
   "atk": 95.0,
   "def": 120.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Bristla": [
  {
   "title": "Thorny Rose Bristla",
   "lv": 27,
   "hp": 96.0,
   "atk": 80.0,
   "def": 80.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Broncherry": [
  {
   "title": "Winds of Spring Broncherry",
   "lv": 23,
   "hp": 144.0,
   "atk": 90.0,
   "def": 100.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Broncherry Aqua": [
  {
   "title": "Waves of Summer Broncherry Aqua",
   "lv": 30,
   "hp": 144.0,
   "atk": 95.0,
   "def": 100.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Bushi": [
  {
   "title": "Vagrant Warrior Bushi",
   "lv": 25,
   "hp": 96.0,
   "atk": 125.0,
   "def": 80.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Bushi Noct": [
  {
   "title": "Samurai of Darkness Bushi Noct",
   "lv": 51,
   "hp": 96.0,
   "atk": 130.0,
   "def": 80.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Caprity": [
  {
   "title": "Walking Farm Caprity",
   "lv": 10,
   "hp": 120.0,
   "atk": 70.0,
   "def": 90.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Caprity Noct": [
  {
   "title": "Tainted Farm Caprity Noct",
   "lv": 23,
   "hp": 120.0,
   "atk": 75.0,
   "def": 90.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Cattiva": [
  {
   "title": "The Cat's Pajamas Cattiva",
   "lv": 10,
   "hp": 84.0,
   "atk": 70.0,
   "def": 70.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 1.05
  }
 ],
 "Cawgnito": [
  {
   "title": "Shadow-Cloaked Schemer Cawgnito",
   "lv": 17,
   "hp": 90.0,
   "atk": 95.0,
   "def": 80.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Celaray": [
  {
   "title": "Soaring Skyfish Celaray",
   "lv": 10,
   "hp": 96.0,
   "atk": 70.0,
   "def": 80.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.77
  }
 ],
 "Celesdir": [
  {
   "title": "Beast of Salvation Celesdir",
   "lv": 60,
   "hp": 144.0,
   "atk": 110.0,
   "def": 100.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Celesdir Noct": [
  {
   "title": "Beast of Chaos Celesdir Noct",
   "lv": 79,
   "hp": 144.0,
   "atk": 115.0,
   "def": 100.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Chikipi": [
  {
   "title": "Plump & Juicy Chikipi",
   "lv": 10,
   "hp": 72.0,
   "atk": 60.0,
   "def": 60.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 1.05
  }
 ],
 "Chillet": [
  {
   "title": "Dancer on the Steppe Chillet",
   "lv": 11,
   "hp": 108.0,
   "atk": 80.0,
   "def": 80.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Chillet Ignis": [
  {
   "title": "Cherry Blossom Dancer Chillet Ignis",
   "lv": 51,
   "hp": 108.0,
   "atk": 85.0,
   "def": 80.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Cinnamoth": [
  {
   "title": "Butterfly Promenade Cinnamoth",
   "lv": 27,
   "hp": 84.0,
   "atk": 80.0,
   "def": 80.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Clovee": [
  {
   "title": "Dubiously Lucky Clovee",
   "lv": 10,
   "hp": 96.0,
   "atk": 65.0,
   "def": 65.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Cremis": [
  {
   "title": "Darling Furball Cremis",
   "lv": 10,
   "hp": 84.0,
   "atk": 70.0,
   "def": 75.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.91
  }
 ],
 "Croajiro": [
  {
   "title": "Harakiri Master Croajiro",
   "lv": 47,
   "hp": 96.0,
   "atk": 100.0,
   "def": 85.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Cryolinx": [
  {
   "title": "Predator of Snowy Peaks Cryolinx",
   "lv": 42,
   "hp": 120.0,
   "atk": 100.0,
   "def": 110.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Cryolinx Terra": [
  {
   "title": "Predator of the Earth Cryolinx Terra",
   "lv": 58,
   "hp": 120.0,
   "atk": 105.0,
   "def": 110.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Daedream": [
  {
   "title": "Dream Eater Daedream",
   "lv": 10,
   "hp": 84.0,
   "atk": 75.0,
   "def": 60.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Dandilord": [
  {
   "title": "Bewitching Lurker Dandilord",
   "lv": 78,
   "hp": 150.0,
   "atk": 135.0,
   "def": 110.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.04,
   "capture": 0.7
  }
 ],
 "Dazemu": [
  {
   "title": "Brilliant Steps Dazemu",
   "lv": 47,
   "hp": 114.0,
   "atk": 90.0,
   "def": 80.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Dazzi": [
  {
   "title": "Born of the Storm Dazzi",
   "lv": 37,
   "hp": 84.0,
   "atk": 80.0,
   "def": 70.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Dazzi Noct": [
  {
   "title": "Born of the Thunderclouds Dazzi Noct",
   "lv": 53,
   "hp": 84.0,
   "atk": 80.0,
   "def": 75.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Depresso": [
  {
   "title": "Several Sleepless Nights Later Depresso",
   "lv": 10,
   "hp": 84.0,
   "atk": 70.0,
   "def": 70.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Digtoise": [
  {
   "title": "Drilling Machine Digtoise",
   "lv": 17,
   "hp": 96.0,
   "atk": 95.0,
   "def": 120.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Dinossom": [
  {
   "title": "Guardian of Blossoming Gardens Dinossom",
   "lv": 10,
   "hp": 132.0,
   "atk": 85.0,
   "def": 90.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Dinossom Lux": [
  {
   "title": "Guardian of Lightning Dinossom Lux",
   "lv": 47,
   "hp": 132.0,
   "atk": 90.0,
   "def": 90.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Direhowl": [
  {
   "title": "Hunter of the Steppe Direhowl",
   "lv": 10,
   "hp": 96.0,
   "atk": 90.0,
   "def": 75.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Dogen": [
  {
   "title": "State of Enlightenment Dogen",
   "lv": 51,
   "hp": 108.0,
   "atk": 100.0,
   "def": 100.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Dualith": [
  {
   "title": "Twinhearted Azure Construct Dualith",
   "lv": 75,
   "hp": 132.0,
   "atk": 105.0,
   "def": 125.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Dualith Noct": [
  {
   "title": "Twinhearted Violet Construct Dualith Noct",
   "lv": 70,
   "hp": 132.0,
   "atk": 110.0,
   "def": 125.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Dumud": [
  {
   "title": "Perpetual Procrastinator Dumud",
   "lv": 14,
   "hp": 120.0,
   "atk": 70.0,
   "def": 95.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Dynamoff": [
  {
   "title": "Buzzy Bundle Dynamoff",
   "lv": 67,
   "hp": 90.0,
   "atk": 85.0,
   "def": 80.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Eidrolon": [
  {
   "title": "Wings of Freedom Eidrolon",
   "lv": 69,
   "hp": 138.0,
   "atk": 125.0,
   "def": 120.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Eikthyrdeer": [
  {
   "title": "Protector of the Herd Eikthyrdeer",
   "lv": 10,
   "hp": 114.0,
   "atk": 80.0,
   "def": 80.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Elizabee": [
  {
   "title": "Empress of the Hive Elizabee",
   "lv": 39,
   "hp": 108.0,
   "atk": 105.0,
   "def": 100.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Elphidran": [
  {
   "title": "Gentle Sky Dragon Elphidran",
   "lv": 30,
   "hp": 132.0,
   "atk": 80.0,
   "def": 90.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Eye of Cthulhu": [
  {
   "title": "Eye of Cthulhu",
   "lv": 45,
   "hp": 110.0,
   "atk": 105.0,
   "def": 95.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 1.0,
   "capture": 1.0
  }
 ],
 "Faleris Aqua": [
  {
   "title": "Sentinel of the Tides Faleris Aqua",
   "lv": 56,
   "hp": 132.0,
   "atk": 110.0,
   "def": 115.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Felbat": [
  {
   "title": "Gloom-Shrouded Bloodsucker Felbat",
   "lv": 31,
   "hp": 120.0,
   "atk": 105.0,
   "def": 110.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Fenglope": [
  {
   "title": "Drifting Cloud Fenglope",
   "lv": 25,
   "hp": 132.0,
   "atk": 110.0,
   "def": 90.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Fenglope Lux": [
  {
   "title": "Drifting Thundercloud Fenglope Lux",
   "lv": 57,
   "hp": 132.0,
   "atk": 115.0,
   "def": 90.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Finsider": [
  {
   "title": "Eyes from the Abyss Finsider",
   "lv": 37,
   "hp": 90.0,
   "atk": 85.0,
   "def": 80.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Flambelle": [
  {
   "title": "Molten Daughter Flambelle",
   "lv": 36,
   "hp": 72.0,
   "atk": 70.0,
   "def": 80.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.77
  }
 ],
 "Flaracle": [
  {
   "title": "Self-Serving Seer Flaracle",
   "lv": 68,
   "hp": 132.0,
   "atk": 125.0,
   "def": 105.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Flopie": [
  {
   "title": "Star of the Flower Beds Flopie",
   "lv": 27,
   "hp": 90.0,
   "atk": 65.0,
   "def": 70.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Foxcicle": [
  {
   "title": "Frostbound Fox Foxcicle",
   "lv": 15,
   "hp": 108.0,
   "atk": 95.0,
   "def": 105.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Foxparks": [
  {
   "title": "Revealer of Paths Foxparks",
   "lv": 10,
   "hp": 78.0,
   "atk": 75.0,
   "def": 70.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.77
  }
 ],
 "Foxparks Cryst": [
  {
   "title": "Icy Blossom Voyager Foxparks Cryst",
   "lv": 15,
   "hp": 78.0,
   "atk": 80.0,
   "def": 70.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.77
  }
 ],
 "Frostallion": [
  {
   "title": "Legendary Steed of Ice Frostallion",
   "lv": 60,
   "hp": 168.0,
   "atk": 140.0,
   "def": 120.0,
   "size": "XL",
   "hpRate": 2.728395,
   "recvRate": 0.18,
   "capture": 0.7
  }
 ],
 "Frostallion Noct": [
  {
   "title": "Legendary Steed of Darkness Frostallion Noct",
   "lv": 65,
   "hp": 168.0,
   "atk": 140.0,
   "def": 135.0,
   "size": "XL",
   "hpRate": 2.728395,
   "recvRate": 0.18,
   "capture": 0.7
  }
 ],
 "Frostplume": [
  {
   "title": "Snowlaced Feather Mantle Frostplume",
   "lv": 42,
   "hp": 132.0,
   "atk": 100.0,
   "def": 100.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Fuack": [
  {
   "title": "Rowdy Wave Ripper Fuack",
   "lv": 10,
   "hp": 72.0,
   "atk": 80.0,
   "def": 60.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.77
  }
 ],
 "Fuddler": [
  {
   "title": "Underground Explorer Fuddler",
   "lv": 10,
   "hp": 78.0,
   "atk": 80.0,
   "def": 50.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Galeclaw": [
  {
   "title": "Proud Courier Galeclaw",
   "lv": 17,
   "hp": 90.0,
   "atk": 85.0,
   "def": 60.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Ghangler": [
  {
   "title": "Temptation in the Deep Ghangler",
   "lv": 47,
   "hp": 108.0,
   "atk": 125.0,
   "def": 105.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Gildane": [
  {
   "title": "Guardian Beast of Twilight Gildane",
   "lv": 58,
   "hp": 144.0,
   "atk": 110.0,
   "def": 110.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Gloopie": [
  {
   "title": "Trickster of the Sea Gloopie",
   "lv": 36,
   "hp": 84.0,
   "atk": 85.0,
   "def": 70.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Gobfin": [
  {
   "title": "Sea Thug Gobfin",
   "lv": 27,
   "hp": 108.0,
   "atk": 90.0,
   "def": 75.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Gobfin Ignis": [
  {
   "title": "Volcano Thug Gobfin Ignis",
   "lv": 36,
   "hp": 108.0,
   "atk": 90.0,
   "def": 75.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Gorirat": [
  {
   "title": "Jungle Punk Gorirat",
   "lv": 27,
   "hp": 108.0,
   "atk": 95.0,
   "def": 90.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Gorirat Terra": [
  {
   "title": "Up for a Brawl Gorirat Terra",
   "lv": 51,
   "hp": 108.0,
   "atk": 100.0,
   "def": 90.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Grintale": [
  {
   "title": "Marshmallow Body Grintale",
   "lv": 17,
   "hp": 132.0,
   "atk": 80.0,
   "def": 80.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Grizzbolt": [
  {
   "title": "Claws of Lightning Grizzbolt",
   "lv": 30,
   "hp": 144.0,
   "atk": 105.0,
   "def": 105.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Gumoss": [
  {
   "title": "Suddenly Transformed Gumoss",
   "lv": 11,
   "hp": 84.0,
   "atk": 70.0,
   "def": 70.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.91
  }
 ],
 "Hangyu": [
  {
   "title": "Bringer of Luck Hangyu",
   "lv": 17,
   "hp": 96.0,
   "atk": 70.0,
   "def": 70.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Helzephyr Lux": [
  {
   "title": "Wings of Netherstorm Helzephyr Lux",
   "lv": 51,
   "hp": 126.0,
   "atk": 125.0,
   "def": 100.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Herbil": [
  {
   "title": "Percussive Maintenance Herbil",
   "lv": 27,
   "hp": 96.0,
   "atk": 75.0,
   "def": 75.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Hoocrates": [
  {
   "title": "Purveyor of Wisdom Hoocrates",
   "lv": 10,
   "hp": 84.0,
   "atk": 70.0,
   "def": 80.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Icelyn": [
  {
   "title": "Icy Smile Icelyn",
   "lv": 42,
   "hp": 114.0,
   "atk": 115.0,
   "def": 105.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Incineram": [
  {
   "title": "Hyena of the Wild Incineram",
   "lv": 36,
   "hp": 114.0,
   "atk": 100.0,
   "def": 85.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Jelliette": [
  {
   "title": "Sunlight Drifter Jelliette",
   "lv": 10,
   "hp": 90.0,
   "atk": 90.0,
   "def": 70.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Jellroy": [
  {
   "title": "Shade Drifter Jellroy",
   "lv": 17,
   "hp": 108.0,
   "atk": 75.0,
   "def": 75.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Jetragon": [
  {
   "title": "Legendary Celestial Dragon Jetragon",
   "lv": 60,
   "hp": 138.0,
   "atk": 140.0,
   "def": 120.0,
   "size": "XL",
   "hpRate": 2.6666667,
   "recvRate": 0.18,
   "capture": 0.7
  }
 ],
 "Jormuntide": [
  {
   "title": "Emperor of the Sea Jormuntide",
   "lv": 55,
   "hp": 156.0,
   "atk": 120.0,
   "def": 100.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Katress": [
  {
   "title": "Phantasmal Feline Katress",
   "lv": 27,
   "hp": 108.0,
   "atk": 105.0,
   "def": 90.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Katress Ignis": [
  {
   "title": "Fire-Licked Feline Katress Ignis",
   "lv": 51,
   "hp": 114.0,
   "atk": 105.0,
   "def": 90.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Kelpsea": [
  {
   "title": "Child of the Deep Kelpsea",
   "lv": 17,
   "hp": 84.0,
   "atk": 70.0,
   "def": 70.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Kelpsea Ignis": [
  {
   "title": "Child of the Molten Depths Kelpsea Ignis",
   "lv": 36,
   "hp": 84.0,
   "atk": 70.0,
   "def": 70.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Kikit": [
  {
   "title": "Armored to the Teeth Kikit",
   "lv": 47,
   "hp": 90.0,
   "atk": 70.0,
   "def": 90.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Killamari": [
  {
   "title": "Emotionless Killamari",
   "lv": 10,
   "hp": 72.0,
   "atk": 60.0,
   "def": 70.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Kingpaca": [
  {
   "title": "Supreme Fluff Commander Kingpaca",
   "lv": 23,
   "hp": 144.0,
   "atk": 85.0,
   "def": 90.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Kingpaca Cryst": [
  {
   "title": "Azure Fluff Commander Kingpaca Cryst",
   "lv": 46,
   "hp": 144.0,
   "atk": 85.0,
   "def": 90.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Kitsun Noct": [
  {
   "title": "Guardian of the Dark Flame Kitsun Noct",
   "lv": 57,
   "hp": 120.0,
   "atk": 115.0,
   "def": 105.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Knocklem": [
  {
   "title": "Suit of Armor Knocklem",
   "lv": 55,
   "hp": 126.0,
   "atk": 110.0,
   "def": 135.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Lamball": [
  {
   "title": "Big Floof Lamball",
   "lv": 10,
   "hp": 84.0,
   "atk": 70.0,
   "def": 70.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 1.05
  }
 ],
 "Lapiron": [
  {
   "title": "Indomitable Racer Lapiron",
   "lv": 65,
   "hp": 84.0,
   "atk": 75.0,
   "def": 80.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Leezpunk": [
  {
   "title": "Self-Proclaimed Genius Leezpunk",
   "lv": 36,
   "hp": 96.0,
   "atk": 80.0,
   "def": 50.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Leezpunk Ignis": [
  {
   "title": "Self-Proclaimed Fashionista Leezpunk Ignis",
   "lv": 36,
   "hp": 96.0,
   "atk": 80.0,
   "def": 50.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Lifmunk": [
  {
   "title": "Coward of the Steppe Lifmunk",
   "lv": 10,
   "hp": 90.0,
   "atk": 70.0,
   "def": 70.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.63
  }
 ],
 "Loupmoon": [
  {
   "title": "Enraptured by Moonlight Loupmoon",
   "lv": 27,
   "hp": 96.0,
   "atk": 100.0,
   "def": 80.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Loupmoon Cryst": [
  {
   "title": "Enraptured by the Frozen Moonlight Loupmoon Cryst",
   "lv": 54,
   "hp": 96.0,
   "atk": 105.0,
   "def": 80.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Lovander": [
  {
   "title": "Pal on the Prowl Lovander",
   "lv": 37,
   "hp": 144.0,
   "atk": 70.0,
   "def": 70.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Lullu": [
  {
   "title": "Primal Source of Hay Fever Lullu",
   "lv": 47,
   "hp": 108.0,
   "atk": 90.0,
   "def": 80.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Lunaris": [
  {
   "title": "Extraterrestrial Lunaris",
   "lv": 35,
   "hp": 108.0,
   "atk": 100.0,
   "def": 90.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Lyleen": [
  {
   "title": "Empress of Lilies Lyleen",
   "lv": 58,
   "hp": 144.0,
   "atk": 120.0,
   "def": 110.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Lyleen Noct": [
  {
   "title": "Empress of the Abyss Lyleen Noct",
   "lv": 49,
   "hp": 138.0,
   "atk": 120.0,
   "def": 115.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Mammorest": [
  {
   "title": "King of the Forest Mammorest",
   "lv": 38,
   "hp": 180.0,
   "atk": 85.0,
   "def": 90.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Mammorest Cryst": [
  {
   "title": "King of the Tundra Mammorest Cryst",
   "lv": 42,
   "hp": 180.0,
   "atk": 85.0,
   "def": 90.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Maraith": [
  {
   "title": "Messenger of Death Maraith",
   "lv": 42,
   "hp": 90.0,
   "atk": 105.0,
   "def": 80.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Mau": [
  {
   "title": "Noble Glimmer Mau",
   "lv": 10,
   "hp": 84.0,
   "atk": 60.0,
   "def": 70.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Mau Cryst": [
  {
   "title": "Serene Glimmer Mau Cryst",
   "lv": 42,
   "hp": 84.0,
   "atk": 65.0,
   "def": 70.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Melpaca": [
  {
   "title": "Pompous Shanks Melpaca",
   "lv": 10,
   "hp": 108.0,
   "atk": 75.0,
   "def": 90.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Menasting": [
  {
   "title": "Unstoppable Stinger Menasting",
   "lv": 44,
   "hp": 120.0,
   "atk": 100.0,
   "def": 130.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Menasting Terra": [
  {
   "title": "Gold-Piercing Spear Menasting Terra",
   "lv": 54,
   "hp": 120.0,
   "atk": 105.0,
   "def": 130.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Moldron": [
  {
   "title": "Scorched Wanderer Moldron",
   "lv": 70,
   "hp": 132.0,
   "atk": 125.0,
   "def": 115.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Moldron Cryst": [
  {
   "title": "Frigid Voyager Moldron Cryst",
   "lv": 78,
   "hp": 132.0,
   "atk": 125.0,
   "def": 120.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Mossanda": [
  {
   "title": "Wanderer of the Forest Mossanda",
   "lv": 27,
   "hp": 120.0,
   "atk": 90.0,
   "def": 90.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Mossanda Lux": [
  {
   "title": "Inheritor of the Storm Mossanda Lux",
   "lv": 31,
   "hp": 120.0,
   "atk": 100.0,
   "def": 100.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Mozzarina": [
  {
   "title": "Prime Beef Mozzarina",
   "lv": 17,
   "hp": 108.0,
   "atk": 50.0,
   "def": 80.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Muffly": [
  {
   "title": "Totally Toasty Muffly",
   "lv": 27,
   "hp": 72.0,
   "atk": 80.0,
   "def": 55.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Munchill": [
  {
   "title": "Walking Refrigerator Munchill",
   "lv": 42,
   "hp": 90.0,
   "atk": 80.0,
   "def": 85.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Mycora": [
  {
   "title": "Cute as a Button Mycora",
   "lv": 78,
   "hp": 126.0,
   "atk": 95.0,
   "def": 90.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Necromus": [
  {
   "title": "Dark Knight of Legend Necromus",
   "lv": 60,
   "hp": 156.0,
   "atk": 145.0,
   "def": 120.0,
   "size": "XL",
   "hpRate": 1.8552631,
   "recvRate": 0.18,
   "capture": 0.7
  }
 ],
 "Needoll": [
  {
   "title": "Prickly Welcome Needoll",
   "lv": 40,
   "hp": 90.0,
   "atk": 85.0,
   "def": 70.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Neptilius": [
  {
   "title": "Legend of the Seas Neptilius",
   "lv": 60,
   "hp": 126.0,
   "atk": 145.0,
   "def": 125.0,
   "size": "XL",
   "hpRate": 3.738395,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Nitemary": [
  {
   "title": "Soul of the Dark Rabbit Nitemary",
   "lv": 60,
   "hp": 126.0,
   "atk": 95.0,
   "def": 105.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Nitewing": [
  {
   "title": "Wings of the Firmament Nitewing",
   "lv": 18,
   "hp": 120.0,
   "atk": 95.0,
   "def": 80.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Nox": [
  {
   "title": "Nighttime Prince Nox",
   "lv": 17,
   "hp": 90.0,
   "atk": 85.0,
   "def": 70.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Nyafia": [
  {
   "title": "Night Shade Hunter Nyafia",
   "lv": 57,
   "hp": 132.0,
   "atk": 100.0,
   "def": 100.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Omascul": [
  {
   "title": "Hundred-Faced Apostle Omascul",
   "lv": 55,
   "hp": 114.0,
   "atk": 105.0,
   "def": 100.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Ophydia": [
  {
   "title": "Pure Bloom Dragon Ophydia",
   "lv": 69,
   "hp": 156.0,
   "atk": 115.0,
   "def": 120.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Paladius": [
  {
   "title": "Holy Knight of Legend Paladius",
   "lv": 60,
   "hp": 156.0,
   "atk": 120.0,
   "def": 145.0,
   "size": "XL",
   "hpRate": 1.8552631,
   "recvRate": 0.18,
   "capture": 0.7
  }
 ],
 "Palumba": [
  {
   "title": "No Dance, No Life Palumba",
   "lv": 47,
   "hp": 126.0,
   "atk": 110.0,
   "def": 115.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Pengullet": [
  {
   "title": "Ate Too Much Pengullet",
   "lv": 10,
   "hp": 84.0,
   "atk": 75.0,
   "def": 70.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Penking": [
  {
   "title": "Pioneer of the Frozen Sea Penking",
   "lv": 15,
   "hp": 114.0,
   "atk": 95.0,
   "def": 95.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Pierdon": [
  {
   "title": "Shambling Vein Pierdon",
   "lv": 50,
   "hp": 120.0,
   "atk": 105.0,
   "def": 120.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Pierdon Cryst": [
  {
   "title": "Shuffling Glacier Pierdon Cryst",
   "lv": 69,
   "hp": 120.0,
   "atk": 110.0,
   "def": 120.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Polapup": [
  {
   "title": "Idol on Ice Polapup",
   "lv": 42,
   "hp": 114.0,
   "atk": 105.0,
   "def": 105.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Prixter Lux": [
  {
   "title": "Thunderboy Prixter Lux",
   "lv": 70,
   "hp": 108.0,
   "atk": 115.0,
   "def": 90.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Prunelia": [
  {
   "title": "Indigo Handmaiden Prunelia",
   "lv": 63,
   "hp": 126.0,
   "atk": 95.0,
   "def": 100.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Puffolt": [
  {
   "title": "Sulky Static Puffolt",
   "lv": 65,
   "hp": 90.0,
   "atk": 80.0,
   "def": 70.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Pyrin": [
  {
   "title": "Steed of Flames Pyrin",
   "lv": 29,
   "hp": 120.0,
   "atk": 95.0,
   "def": 90.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Pyrin Noct": [
  {
   "title": "Steed of Darkness Pyrin Noct",
   "lv": 36,
   "hp": 120.0,
   "atk": 95.0,
   "def": 90.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Quivern": [
  {
   "title": "Snow-White Soarer Quivern",
   "lv": 42,
   "hp": 126.0,
   "atk": 100.0,
   "def": 100.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Quivern Botan": [
  {
   "title": "Evergreen Flyer Quivern Botan",
   "lv": 51,
   "hp": 126.0,
   "atk": 105.0,
   "def": 100.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Ragnahawk": [
  {
   "title": "Wings of Inferno Ragnahawk",
   "lv": 36,
   "hp": 114.0,
   "atk": 105.0,
   "def": 120.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Rayhound": [
  {
   "title": "Electro-Charged Zoomies Rayhound",
   "lv": 37,
   "hp": 108.0,
   "atk": 100.0,
   "def": 80.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Reindrix": [
  {
   "title": "Frosthorn Beast Reindrix",
   "lv": 42,
   "hp": 120.0,
   "atk": 85.0,
   "def": 110.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Renjishi": [
  {
   "title": "Scorching Ovation Renjishi",
   "lv": 78,
   "hp": 126.0,
   "atk": 120.0,
   "def": 100.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Reptyro": [
  {
   "title": "Lava-Devouring Juggernaut Reptyro",
   "lv": 50,
   "hp": 132.0,
   "atk": 105.0,
   "def": 120.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Reptyro Cryst": [
  {
   "title": "Ice-Breaking Juggernaut Reptyro Cryst",
   "lv": 42,
   "hp": 132.0,
   "atk": 105.0,
   "def": 130.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Ribbuny": [
  {
   "title": "Heart-Melting Smile Ribbuny",
   "lv": 17,
   "hp": 90.0,
   "atk": 65.0,
   "def": 70.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Ribbuny Botan": [
  {
   "title": "Sparkling Smile Ribbuny Botan",
   "lv": 53,
   "hp": 96.0,
   "atk": 65.0,
   "def": 70.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Robinquill": [
  {
   "title": "Archer of the Forest Robinquill",
   "lv": 27,
   "hp": 108.0,
   "atk": 105.0,
   "def": 80.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Robinquill Terra": [
  {
   "title": "Archer of the Sands Robinquill Terra",
   "lv": 37,
   "hp": 108.0,
   "atk": 105.0,
   "def": 80.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Rooby": [
  {
   "title": "Chief of the Herd Rooby",
   "lv": 10,
   "hp": 90.0,
   "atk": 70.0,
   "def": 75.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.77
  }
 ],
 "Rushoar": [
  {
   "title": "Woodland Ruffian Rushoar",
   "lv": 10,
   "hp": 96.0,
   "atk": 70.0,
   "def": 70.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Shroomer": [
  {
   "title": "Creeping Mushroom Shroomer",
   "lv": 47,
   "hp": 132.0,
   "atk": 80.0,
   "def": 90.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Shroomer Noct": [
  {
   "title": "Dangerous Mushroom Shroomer Noct",
   "lv": 51,
   "hp": 132.0,
   "atk": 85.0,
   "def": 90.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Sibelyx": [
  {
   "title": "Pallid Lady Sibelyx",
   "lv": 40,
   "hp": 132.0,
   "atk": 90.0,
   "def": 100.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Silvance": [
  {
   "title": "Immortal Shade Silvance",
   "lv": 78,
   "hp": 168.0,
   "atk": 120.0,
   "def": 110.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.04,
   "capture": 0.7
  }
 ],
 "Silvegis": [
  {
   "title": "Guardian Dragon of Ironclad Silvegis",
   "lv": 59,
   "hp": 144.0,
   "atk": 110.0,
   "def": 115.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Slowatt": [
  {
   "title": "Shockingly Laid-Back Slowatt",
   "lv": 66,
   "hp": 96.0,
   "atk": 75.0,
   "def": 70.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Smokie": [
  {
   "title": "Jet-Black Little Hero Smokie",
   "lv": 60,
   "hp": 102.0,
   "atk": 90.0,
   "def": 85.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Snock": [
  {
   "title": "Sluggish Blue Bolt Snock",
   "lv": 65,
   "hp": 78.0,
   "atk": 70.0,
   "def": 75.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Sootseer": [
  {
   "title": "Flickering Flame Sootseer",
   "lv": 51,
   "hp": 126.0,
   "atk": 125.0,
   "def": 90.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Souffline": [
  {
   "title": "Windborne Seedling Souffline",
   "lv": 65,
   "hp": 84.0,
   "atk": 75.0,
   "def": 60.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Splatterina": [
  {
   "title": "Crimson Butcher Splatterina",
   "lv": 58,
   "hp": 114.0,
   "atk": 115.0,
   "def": 105.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Starryon": [
  {
   "title": "Midnight Blue Mane Starryon",
   "lv": 57,
   "hp": 132.0,
   "atk": 100.0,
   "def": 100.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Surfent": [
  {
   "title": "The Ocean's Wrath Surfent",
   "lv": 17,
   "hp": 108.0,
   "atk": 90.0,
   "def": 80.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Surfent Terra": [
  {
   "title": "The Desert's Wrath Surfent Terra",
   "lv": 37,
   "hp": 108.0,
   "atk": 90.0,
   "def": 100.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Suzaku": [
  {
   "title": "Ruler of the Crimson Dawn Suzaku",
   "lv": 45,
   "hp": 144.0,
   "atk": 105.0,
   "def": 105.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Suzaku Aqua": [
  {
   "title": "Ruler of the Cobalt Dusk Suzaku Aqua",
   "lv": 42,
   "hp": 150.0,
   "atk": 105.0,
   "def": 105.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Sweepa": [
  {
   "title": "King of the Floof Sweepa",
   "lv": 11,
   "hp": 120.0,
   "atk": 90.0,
   "def": 90.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Tanzee": [
  {
   "title": "Dexterous Primate Tanzee",
   "lv": 10,
   "hp": 96.0,
   "atk": 70.0,
   "def": 70.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.77
  }
 ],
 "Tarantriss": [
  {
   "title": "Tactician of the Thread Realm Tarantriss",
   "lv": 35,
   "hp": 132.0,
   "atk": 100.0,
   "def": 100.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Teafant": [
  {
   "title": "Adorable Watering Can Teafant",
   "lv": 10,
   "hp": 84.0,
   "atk": 60.0,
   "def": 70.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.91
  }
 ],
 "Tetroise": [
  {
   "title": "Sandsea Monolith Tetroise",
   "lv": 55,
   "hp": 114.0,
   "atk": 100.0,
   "def": 135.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Tetroise Primo": [
  {
   "title": "Sandsea Wardenstone Tetroise Primo",
   "lv": 60,
   "hp": 114.0,
   "atk": 100.0,
   "def": 140.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Tocotoco": [
  {
   "title": "Boom or Bust Tocotoco",
   "lv": 17,
   "hp": 72.0,
   "atk": 75.0,
   "def": 70.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Tombat": [
  {
   "title": "Trickster Tombat",
   "lv": 15,
   "hp": 114.0,
   "atk": 95.0,
   "def": 80.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.7
  }
 ],
 "Tropicaw": [
  {
   "title": "Blooming Crooner Tropicaw",
   "lv": 65,
   "hp": 102.0,
   "atk": 85.0,
   "def": 90.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Turtacle": [
  {
   "title": "Mini Fortress Turtacle",
   "lv": 27,
   "hp": 90.0,
   "atk": 75.0,
   "def": 115.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Univolt": [
  {
   "title": "Swift Deity Univolt",
   "lv": 31,
   "hp": 96.0,
   "atk": 105.0,
   "def": 105.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.63
  }
 ],
 "Vaelet": [
  {
   "title": "Voice of the Violets Vaelet",
   "lv": 27,
   "hp": 120.0,
   "atk": 100.0,
   "def": 120.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Valentail": [
  {
   "title": "Plays Both Sides Valentail",
   "lv": 65,
   "hp": 90.0,
   "atk": 80.0,
   "def": 70.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Vanwyrm": [
  {
   "title": "Aerial Marauder Vanwyrm",
   "lv": 36,
   "hp": 108.0,
   "atk": 115.0,
   "def": 90.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Vanwyrm Cryst": [
  {
   "title": "Marauder of Frozen Skies Vanwyrm Cryst",
   "lv": 42,
   "hp": 108.0,
   "atk": 120.0,
   "def": 95.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Verdash": [
  {
   "title": "Gale of the Forest Verdash",
   "lv": 35,
   "hp": 108.0,
   "atk": 115.0,
   "def": 90.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Vixy": [
  {
   "title": "Star of the Steppe Vixy",
   "lv": 10,
   "hp": 84.0,
   "atk": 70.0,
   "def": 70.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.48,
   "capture": 0.91
  }
 ],
 "Warsect Terra": [
  {
   "title": "Gold-Armored Warrior Warsect Terra",
   "lv": 59,
   "hp": 144.0,
   "atk": 105.0,
   "def": 120.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Whalaska": [
  {
   "title": "Gentle Ice Lance Whalaska",
   "lv": 55,
   "hp": 126.0,
   "atk": 115.0,
   "def": 110.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Whalaska Ignis": [
  {
   "title": "Gentle Crimson Lance Whalaska Ignis",
   "lv": 58,
   "hp": 126.0,
   "atk": 120.0,
   "def": 110.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Wistella": [
  {
   "title": "Mantle of the Night Sky Wistella",
   "lv": 66,
   "hp": 96.0,
   "atk": 90.0,
   "def": 60.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Wixen": [
  {
   "title": "Fire-Licked Furball Wixen",
   "lv": 28,
   "hp": 108.0,
   "atk": 110.0,
   "def": 80.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Wixen Noct": [
  {
   "title": "Phantasmal Furball Wixen Noct",
   "lv": 51,
   "hp": 108.0,
   "atk": 110.0,
   "def": 85.0,
   "size": "L",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Woolipop": [
  {
   "title": "Giant Cotton Candy Woolipop",
   "lv": 17,
   "hp": 84.0,
   "atk": 70.0,
   "def": 90.0,
   "size": "M",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Wumpo": [
  {
   "title": "Guardian of the Snowy Fields Wumpo",
   "lv": 42,
   "hp": 168.0,
   "atk": 80.0,
   "def": 100.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Wumpo Botan": [
  {
   "title": "Guardian of the Grassy Fields Wumpo Botan",
   "lv": 38,
   "hp": 168.0,
   "atk": 80.0,
   "def": 110.0,
   "size": "XL",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ],
 "Yakumo": [
  {
   "title": "Unwavering Loyalty Yakumo",
   "lv": 47,
   "hp": 102.0,
   "atk": 85.0,
   "def": 85.0,
   "size": "S",
   "hpRate": 1.0,
   "recvRate": 0.24,
   "capture": 0.7
  }
 ]
};
