/** GENERATED by tools/gen_data_changes.py — DO NOT EDIT.
 * What moved between the last shipped item data and this one.
 * Every line is the difference between two files we hold; nothing
 * here is written by hand. */
export interface DataChange {
  /** the day the refresh was generated */
  when: string;
  /** what the refresh was, in a player's words */
  label: string;
  /** one line per kind of change, biggest first */
  lines: string[];
  itemsAdded: number;
  itemsRemoved: number;
  itemsChanged: number;
}

export const DATA_CHANGES: DataChange = {
 "when": "2026-08-20",
 "label": "The stat fruits say what they do, and 5 weapons got a source",
 "lines": [
  "5 items gained facts they had none of — Grappling Gun",
  "4 effects changed — Life Fruit, Power Fruit, Seafood Pasta, Stout Fruit"
 ],
 "itemsAdded": 5,
 "itemsRemoved": 0,
 "itemsChanged": 4
};
