/** GENERATED by tools/gen_element_chart.py — do not edit.
 *
 * The game's element strengths chart. Wiki-measured, not datamined —
 * accepted only because two independent wikis agree cell-for-cell, the
 * table is perfectly antisymmetric, and its vocabulary equals our pals
 * data exactly. Provenance (both revision ids) in data/elements_1_0.json.
 *
 * Reading it: an attack of element A deals double to every element in
 * chart[A].strong and half to every element in chart[A].weak; per-element
 * multipliers on a dual-element pal multiply, so strong+weak cancels to
 * even. A skill matching the defender's own element is even too. No pal
 * in our data takes 4x or 0.25x (counted at generation time, 299 pals).
 */

export interface ElementMatchups {
  strong: string[];
  weak: string[];
}

export const ELEMENT_CHART_SOURCE = "palworld.wiki.gg Elements (revid 30073) + palworld.fandom.com Elements (revid 29952), fetched 2026-08-18; accepted only because both agree cell-for-cell AND the table is perfectly antisymmetric AND its vocabulary equals pals_1_0.json's 9 elements. Wiki-measured, not datamined: no pinned raw dump publishes the game's element table (atlas build-24575149 manifest checked, 11 tables, none of them elements; paldb /Elements is prose only).";

export const ELEMENT_CHART: Record<string, ElementMatchups> = {
  Dark: { strong: ['Neutral'], weak: ['Dragon'] },
  Dragon: { strong: ['Dark'], weak: ['Ice'] },
  Electric: { strong: ['Water'], weak: ['Ground'] },
  Fire: { strong: ['Grass', 'Ice'], weak: ['Water'] },
  Grass: { strong: ['Ground'], weak: ['Fire'] },
  Ground: { strong: ['Electric'], weak: ['Grass'] },
  Ice: { strong: ['Dragon'], weak: ['Fire'] },
  Neutral: { strong: [], weak: ['Dark'] },
  Water: { strong: ['Fire'], weak: ['Electric'] },
};
