/** GENERATED by tools/fetch_map_icons.py — DO NOT EDIT.
 * The GAME's own map symbols, one per POI layer, so a marker on our
 * map reads the same as the marker the player already knows.
 * Sources: the game's item art via mlg404/palworld-paldex-api (MIT,
 * 96px) for materials the in-game map never draws; jeankassio/
 * PalMiniMap (MIT, 64-100px) where a map symbol corresponds;
 * otherwise Nifrendil/pal-atlas (MIT). */
/* eslint-disable @typescript-eslint/no-require-imports */

export const MAP_ICONS: Record<string, number> = {
  alpha_pals: require('../../assets/mapicons/alpha_pals.png'),
  bounty_targets: require('../../assets/mapicons/bounty_targets.png'),
  chest: require('../../assets/mapicons/chest.png'),
  coal: require('../../assets/mapicons/coal.png'),
  crude_oil: require('../../assets/mapicons/crude_oil.png'),
  dungeon: require('../../assets/mapicons/dungeon.png'),
  egg: require('../../assets/mapicons/egg.png'),
  fast_travel: require('../../assets/mapicons/fast_travel.png'),
  merchant: require('../../assets/mapicons/merchant.png'),
  mushrooms: require('../../assets/mapicons/mushrooms.png'),
  note: require('../../assets/mapicons/note.png'),
  npc: require('../../assets/mapicons/npc.png'),
  ore: require('../../assets/mapicons/ore.png'),
  pal_effigy: require('../../assets/mapicons/pal_effigy.png'),
  pal_merchant: require('../../assets/mapicons/pal_merchant.png'),
  paldium: require('../../assets/mapicons/paldium.png'),
  pure_quartz: require('../../assets/mapicons/pure_quartz.png'),
  red_berries: require('../../assets/mapicons/red_berries.png'),
  sealed_realm: require('../../assets/mapicons/sealed_realm.png'),
  skill_fruit: require('../../assets/mapicons/skill_fruit.png'),
  soralite: require('../../assets/mapicons/soralite.png'),
  sulfur: require('../../assets/mapicons/sulfur.png'),
  syndicate_tower: require('../../assets/mapicons/syndicate_tower.png'),
};
