/** GENERATED by tools/extract_map_data.py — DO NOT EDIT.
 * Map regions, projection constants and provenance.
 * Locations: Awy64/palworld-atlas-data build 24575149 (official
 * dedicated-server package, 2026-08-12) + Nifrendil/pal-atlas POIs.
 * Projected with the game's own DT_WorldMapUIData bounds; proof and
 * residual bound in tools/verify_map_projection.py. */
export interface MapRegion {
  id: 'palpagos' | 'tree';
  name: string;
  /** world bounds from the game's DT_WorldMapUIData (exactly square) */
  minX: number; maxX: number; minY: number; maxY: number;
  /** native texture size we tile from */
  size: number;
  /** deepest tile zoom level in the bundled pyramid */
  maxZ: number;
}

export const MAP_REGIONS: MapRegion[] = [
  { id: 'palpagos', name: 'Palpagos Islands',
    minX: -1099400.0, maxX: 349400.0, minY: -724400.0, maxY: 724400.0,
    size: 4096, maxZ: 3 },
  { id: 'tree', name: 'The World Tree',
    minX: 347351.5, maxX: 689148.5, minY: -818197.0, maxY: -476400.0,
    size: 4096, maxZ: 3 },
];

/** The coordinate readout the GAME shows the player, so our numbers
 *  match the ones on his screen. Confirmed identical across palcalc,
 *  pal-atlas and atlas-data. */
export const MAP_READOUT = { translX: 123930.0, translY: 157935.0, scale: 458.52 } as const;

export const MAP_DATA_BUILD = '24575149';
