/**
 * The item facts layer — recipes, tech (level + point cost + ancient),
 * capture power, effects, sources, resolved descriptions. Generated by
 * tools/gen_item_facts.py from the paldb page sweep + tech tree, accepted
 * only at exact internal-id identity with the atlas backbone.
 */
import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

type Facts = {
  counts: Record<string, number>;
  mapObjectNames: Record<string, string>;
  facts: Record<string, {
    desc?: string;
    recipe?: { id: string; n: number }[];
    recipesMore?: { id: string; n: number }[][];
    tech?: { level: number; cost?: number; ancient?: boolean };
    capture?: string;
    effects?: [string, string][];
    drops?: { src: string; n: string; p: string }[];
    boxes?: { src: string; n: string; p: string }[];
    shops?: string[];
  }>;
};

const load = (rel: string): Facts =>
  JSON.parse(readFileSync(join(__dirname, rel), 'utf8')) as Facts;

const F = load('../public/data/item_facts_1_0.json');
const ITEMS = (JSON.parse(readFileSync(
  join(__dirname, '../public/data/items_1_0.json'), 'utf8')) as {
  items: Record<string, { name: string }>;
}).items;

describe('the validation doctrine held', () => {
  it('zero refusals on recipes and tech — everything shipped resolved', () => {
    expect(F.counts.recipeRefusals).toBe(0);
    expect(F.counts.techRefusals).toBe(0);
  });

  it('the layer is broad, not a sample', () => {
    expect(Object.keys(F.facts).length).toBeGreaterThanOrEqual(1700);
    expect(F.counts.withRecipe).toBeGreaterThanOrEqual(1200);
    expect(F.counts.tech).toBeGreaterThanOrEqual(350);
    expect(F.counts.boxes).toBeGreaterThanOrEqual(8000);
  });

  it('every recipe ingredient resolves against the backbone', () => {
    for (const [id, f] of Object.entries(F.facts)) {
      for (const r of f.recipe ?? []) {
        expect(ITEMS[r.id], `${id} recipe uses unknown ${r.id}`).toBeDefined();
        expect(r.n).toBeGreaterThan(0);
      }
    }
  });
});

describe('the facts agree with what we already verified independently', () => {
  it('the Cake recipe is the Reference tab’s 5/8/7/8/2', () => {
    const cake = F.facts.Cake?.recipe;
    expect(cake).toEqual([
      { id: 'Flour', n: 5 },
      { id: 'Berries', n: 8 },
      { id: 'Milk', n: 7 },
      { id: 'Egg', n: 8 },
      { id: 'Honey', n: 2 },
    ]);
  });

  it('the Assault Rifle unlocks at level 45, costed, not ancient', () => {
    const t = F.facts.AssaultRifle_Default1?.tech;
    expect(t?.level).toBe(45);
    expect(t?.cost).toBeGreaterThan(0);
    expect(t?.ancient).toBeUndefined();
  });

  it('sphere capture powers are the page-header values', () => {
    expect(F.facts.PalSphere?.capture).toBe('7');
    expect(F.facts.PalSphere_Mega?.capture).toBe('14');
    expect(F.facts.PalSphere_Legend?.capture).toBe('38');
  });

  it('Cake feeds like the game says', () => {
    expect(F.facts.Cake?.effects).toContainEqual(['Nutrition', '656']);
    expect(F.facts.Cake?.effects).toContainEqual(['SAN', '82']);
  });
});

describe('sources speak in a player’s words', () => {
  it('no shipped source string carries an internal token', () => {
    for (const [id, f] of Object.entries(F.facts)) {
      for (const row of [...(f.drops ?? []), ...(f.boxes ?? [])]) {
        expect(row.src, `${id} leaks: ${row.src}`).not.toMatch(/_/);
      }
      for (const shop of f.shops ?? []) {
        expect(shop, `${id} shop leaks: ${shop}`).not.toMatch(/_/);
      }
    }
  });

  it('shops collapse onto merchant families and real place names', () => {
    const all = new Set<string>();
    for (const f of Object.values(F.facts)) {
      for (const shop of f.shops ?? []) all.add(shop);
    }
    // six merchant families + a handful of named settlements — never a
    // numbered internal shop id
    expect(all.size).toBeLessThanOrEqual(12);
    for (const sh of all) expect(sh, sh).not.toMatch(/\d/);
    expect([...all].some((sh) => sh.includes('merchant'))).toBe(true);
  });
});

describe('tier crafts prove their own attribution', () => {
  it('the Assault Rifle’s higher tiers each name product, schematic and cost', () => {
    const crafts = (F.facts.AssaultRifle_Default1 as unknown as {
      crafts?: { product: string; schematic?: string;
        mats: { id: string; n: number }[] }[];
    }).crafts;
    expect(crafts?.length).toBe(4);
    expect(crafts![0].product).toBe('AssaultRifle_Default2');
    expect(crafts![0].schematic).toBe('Blueprint_AssaultRifle_Default2');
    expect(crafts![0].mats).toContainEqual({ id: 'IronIngot', n: 50 });
    expect(crafts![3].product).toBe('AssaultRifle_Default5');
    expect(crafts![3].mats).toContainEqual({ id: 'PalCrystal_Ex', n: 4 });
  });

  it('every craft resolves entirely against the backbone', () => {
    for (const [id, f] of Object.entries(F.facts)) {
      const crafts = (f as unknown as {
        crafts?: { product: string; schematic?: string;
          mats: { id: string; n: number }[] }[];
      }).crafts ?? [];
      for (const c of crafts) {
        expect(ITEMS[c.product], `${id} craft product`).toBeDefined();
        if (c.schematic) expect(ITEMS[c.schematic], `${id} schematic`).toBeDefined();
        for (const m of c.mats) {
          expect(ITEMS[m.id], `${id} craft material ${m.id}`).toBeDefined();
          expect(m.n).toBeGreaterThan(0);
        }
      }
    }
  });
});

describe('research lines say what an item is for', () => {
  it('Ancient Civilization Parts feeds the lab bonuses by name', () => {
    const id = Object.keys(ITEMS).find(
      (i) => ITEMS[i].name === 'Ancient Civilization Parts');
    expect(id).toBeDefined();
    const r = (F.facts[id!] as unknown as { research?: string[] }).research;
    expect(r).toBeDefined();
    expect(r).toContain('Handiwork Speed Lv4');
    expect(r!.length).toBeLessThanOrEqual(15);
  });

  it('research names are plain words, never ids', () => {
    for (const [id, f] of Object.entries(F.facts)) {
      for (const r of (f as unknown as { research?: string[] }).research ?? []) {
        expect(r, `${id} research leaks: ${r}`).not.toMatch(/_|[a-z][A-Z]/);
      }
    }
  });
});

describe('equipment passives resolve to the game’s names', () => {
  it('every passive id the stats layer uses has a display name', () => {
    const stats = JSON.parse(readFileSync(
      join(__dirname, '../public/data/item_stats_1_0.json'), 'utf8')) as {
      stats: Record<string, { passives?: string[] }>;
    };
    const names = (F as unknown as {
      equipPassiveNames: Record<string, string>;
    }).equipPassiveNames;
    const used = new Set<string>();
    for (const v of Object.values(stats.stats)) {
      for (const p of v.passives ?? []) used.add(p);
    }
    expect(used.size).toBeGreaterThanOrEqual(20);
    for (const p of used) {
      expect(names[p], `no display name for ${p}`).toBeDefined();
      expect(names[p]).not.toMatch(/_/);
    }
    // the probe's own canary
    expect(names.TemperatureResist_Cold2).toBe('Cold Resistance Lv. 2');
  });
});

describe('descriptions shipped clean', () => {
  it('no shipped description carries a raw placeholder tag', () => {
    for (const [id, f] of Object.entries(F.facts)) {
      if (f.desc) {
        expect(f.desc, id).not.toMatch(/<[a-zA-Z]+ id=\|/);
      }
    }
  });

  it('Bread reads like a sentence, not markup', () => {
    expect(F.facts.Pan?.desc).toContain('Bread');
    expect(F.facts.Pan?.desc).toContain('Flour');
    expect(F.facts.Pan?.desc).not.toContain('<itemName');
  });

  it('the map-object names harvested at exact identity', () => {
    // probed live 2026-08-19: MapObjects/WeaponFactory_Dirty_02 renders
    // as "Weapon Assembly Line" in paldb's own substitution
    expect(F.mapObjectNames.WeaponFactory_Dirty_02).toBe('Weapon Assembly Line');
    expect(Object.keys(F.mapObjectNames).length).toBeGreaterThanOrEqual(30);
  });
});

describe('three copies, byte-identical (the E139 law)', () => {
  it('canonical, mobile and web copies match', () => {
    const a = readFileSync(join(__dirname, '../../data/item_facts_1_0.json'), 'utf8');
    const b = readFileSync(join(__dirname, '../../mobile/src/data/item_facts_1_0.json'), 'utf8');
    const c = readFileSync(join(__dirname, '../public/data/item_facts_1_0.json'), 'utf8');
    expect(a).toBe(b);
    expect(b).toBe(c);
  });
});
